### ISSUE TITLE
[NEW-INITIATIVE]: לא עוצרים עד שמנצחים

### ISSUE THREAD

**Issue by ohadschn** [4tals/LinksForIsrael#110]
### Initiative Name
menatzchim

### Initiative Description
אנחנו אזרחים שרוצים – כמו כולם – לראות נצחון אמיתי.

### Initiative Details
מי אנחנו?
אנחנו אזרחים שרוצים – כמו כולם – לראות נצחון אמיתי.
מאחורי היוזמה עומדת שורה של אנשי ציבור, רבנים ומובילי דעת קהל,
פעילים חברתיים ואנשים שאכפת להם.

מה המטרה שלנו?
המטרה היא לבטא קריאה ציבורית מקיפה ורחבה, דעת קהל מכל גווני הקשת –
המחזקת את הנהגת המדינה והצבא להלחם עד לנצחון האמיתי.
כדי להבהיר את הדרך, כדי לא להיכנע ללחצים מבית ומחוץ, כדי לא לאפשר לאף אחד לחזור על טעויות העבר ולהסתפק בחצי-עבודה – אנחנו מגדירים מראש את היעדים של הנצחון. ודורשים לבצע אותם, עד לנצחון המלא בעזרת השם.

למה זה חשוב?
הכאב נורא ואיום. הזעם אדיר. כולם מדברים על נצחון והכרעה. לעולם לא עוד!
אבל אסור להסתפק במילים כלליות והצהרות ללא תוכן.
חייבים לדרוש, כבר עכשיו, יעדים ברורים - דרישה שנוכל לעמוד מאחוריה כחומה בצורה,
גם בעוד שבוע ועוד חודש והלאה.
כדי שיהיה ברור מעכשיו ולתמיד - בלי השגת היעדים האלו זה לא נצחון.
ואסור להפסיק לפני הנצחון.

מה היעדים?
נצחון אמיתי חייב לכלול את המרכיבים הבאים עד הסוף:
חיסול המחבלים - להרוג את כל החברים בארגוני הטרור, מהמנהיגים ועד אחרון המחבלים.
טיהור השטח - החרמת כל אמצעי הלחימה מכל מרחב רצועת עזה.
שליטה מלאה - בסוף אנחנו חייבים לשלוט בעזה, שליטה יהודית מלאה, מכאן ולתמיד.

מה אנחנו עושים?
מפיקים ומפיצים חומרי הסברה. נמצאים בשטח ברחובות ובצמתים עם שילוט וסטיקרים,
יוצרים דעת קהל בתקשורת וברשתות, מארגנים מאהל שביתה מול הקריה עם משפחות החטופים ועוד הרבה הרבה רעיונות.

### Initiative Validation Details
* https://www.inn.co.il/news/616983
* https://www.guidestar.org.il/organization/580622041

### Initiative Category
StrategicCommunication/Main

### Initiative main URL
https://givechak.co.il/menatzchim

### Initiative Website
https://givechak.co.il/menatzchim

### Initiative WhatsApp
https://chat.whatsapp.com/L1tGwh6LcVk13tX6ak59Xi

### Initiative Form
https://docs.google.com/forms/d/e/1FAIpQLScRx5EvlH76S3UMqHS47nSijBOqaId1JhDE-1tl1DdQtKiCRQ/viewform

### Initiative logo
https://static.tickchak.co.il/all/dln_00DNaVjdrkUR35EdpVXc0pVU0YUdwUnQnRnR1I2aERHa1FjYmFXay50KmZzY_090zdopFT2EDa5Z1U1wGNBNne5k2YzVzS.jpg_65ed8799-213e-4a49-91af-4f5131c62577.jpg

**Comment by 4tal** [comment]
Missing information

**Comment by ohadschn** [comment]
I guess it's best to go through their main website anyway (https://www.recruiting-with-love.org/)

**Comment by ohadschn** [comment]
@4tal note the form belonged to a different initiative,updated the details properly
