### ISSUE TITLE
[NEW-INITIATIVE]: מוקד תרומת ציוד מיגון אישי בכמויות גדולות לצה"ל

### ISSUE THREAD

**Issue by ohadschn** [4tals/LinksForIsrael#115]
### Initiative Name
IdfLargeEquipmentDonation

### Initiative Description
משרד הביטחון, צה"ל והאגודה למען החייל נפתח מוקד לקליטת פניות של גורמים המבקשים לתרום ציוד מיגון אישי בכמויות גדולות לצה"ל.

### Initiative Details
על אף הבהרות צה"ל כי אין מחסור בציוד מיגון אישי ללוחמים, גורמים רבים בארץ ובעולם, פונים מאז פרוץ המלחמה ומבקשים לתרום ציוד לחיילים.

אזרחים שכבר יש בידיהם ציוד מיגון אישי תקני בכמויות גדולות ומעוניינים שמערכת הביטחון תבדוק אותו, מוזמנים לפנות למוקד לשם בדיקת הצורך בציוד והתאמתו לצרכי ותקני צה"ל. 

פניות שיתקבלו לציוד מיגון אישי בכמויות גדולות בלבד, ייבחנו בידי גורמי מקצוע. תרומות שימצאו מתאימות לצרכים ולתקנים, ייקלטו כתרומה בצה"ל באמצעות האגודה למען החייל. 

יודגש כי אזרחים המעוניינים לתרום כספים לרווחת חיילי צה"ל, יכולים לפנות לאגודה למען החייל בטלפון 3399*. כל התרומות שיאספו יועברו לרווחת החיילים בהתאם לצרכים שיוגדרו ע"י צה"ל.    

### Initiative Validation Details
https://www.idf.il/%D7%90%D7%AA%D7%A8%D7%99-%D7%99%D7%97%D7%99%D7%93%D7%95%D7%AA/%D7%99%D7%95%D7%9E%D7%9F-%D7%94%D7%9E%D7%9C%D7%97%D7%9E%D7%94/%D7%9B%D7%9C-%D7%94%D7%9B%D7%AA%D7%91%D7%95%D7%AA/%D7%94%D7%A4%D7%A6%D7%95%D7%AA/%D7%9E%D7%A9%D7%A8%D7%93-%D7%94%D7%91%D7%99%D7%98%D7%97%D7%95%D7%9F-%D7%A6%D7%94-%D7%9C-%D7%94%D7%90%D7%92%D7%95%D7%93%D7%94-%D7%9C%D7%9E%D7%A2%D7%9F-%D7%94%D7%97%D7%99%D7%99%D7%9C-%D7%9E%D7%95%D7%A7%D7%93-%D7%A6%D7%99%D7%95%D7%93-%D7%9E%D7%99%D7%92%D7%95%D7%9F-%D7%95%D7%A1%D7%98%D7%99%D7%9D-%D7%9C%D7%97%D7%99%D7%9E%D7%94/

### Initiative Category
Supplies/Donation

### Initiative main URL
https://www.idf.il/%D7%90%D7%AA%D7%A8%D7%99-%D7%99%D7%97%D7%99%D7%93%D7%95%D7%AA/%D7%99%D7%95%D7%9E%D7%9F-%D7%94%D7%9E%D7%9C%D7%97%D7%9E%D7%94/%D7%9B%D7%9C-%D7%94%D7%9B%D7%AA%D7%91%D7%95%D7%AA/%D7%94%D7%A4%D7%A6%D7%95%D7%AA/%D7%9E%D7%A9%D7%A8%D7%93-%D7%94%D7%91%D7%99%D7%98%D7%97%D7%95%D7%9F-%D7%A6%D7%94-%D7%9C-%D7%94%D7%90%D7%92%D7%95%D7%93%D7%94-%D7%9C%D7%9E%D7%A2%D7%9F-%D7%94%D7%97%D7%99%D7%99%D7%9C-%D7%9E%D7%95%D7%A7%D7%93-%D7%A6%D7%99%D7%95%D7%93-%D7%9E%D7%99%D7%92%D7%95%D7%9F-%D7%95%D7%A1%D7%98%D7%99%D7%9D-%D7%9C%D7%97%D7%99%D7%9E%D7%94/

### Initiative Website
https://www.idf.il/%D7%90%D7%AA%D7%A8%D7%99-%D7%99%D7%97%D7%99%D7%93%D7%95%D7%AA/%D7%99%D7%95%D7%9E%D7%9F-%D7%94%D7%9E%D7%9C%D7%97%D7%9E%D7%94/%D7%9B%D7%9C-%D7%94%D7%9B%D7%AA%D7%91%D7%95%D7%AA/%D7%94%D7%A4%D7%A6%D7%95%D7%AA/%D7%9E%D7%A9%D7%A8%D7%93-%D7%94%D7%91%D7%99%D7%98%D7%97%D7%95%D7%9F-%D7%A6%D7%94-%D7%9C-%D7%94%D7%90%D7%92%D7%95%D7%93%D7%94-%D7%9C%D7%9E%D7%A2%D7%9F-%D7%94%D7%97%D7%99%D7%99%D7%9C-%D7%9E%D7%95%D7%A7%D7%93-%D7%A6%D7%99%D7%95%D7%93-%D7%9E%D7%99%D7%92%D7%95%D7%9F-%D7%95%D7%A1%D7%98%D7%99%D7%9D-%D7%9C%D7%97%D7%99%D7%9E%D7%94/

### Initiative phone
073-3538888

### Initiative e-mail
Trumot_migun@mod.gov.il

**Comment by 4tal** [comment]
I prefer civil initiatives. Not sure if we should add it.

**Comment by ohadschn** [comment]
The way I see it, we're the one stop shop for anyone who is looking to offer help or get help.
If that help happens to be government-provided, so be it...
For example https://www.recruiting-with-love.org belongs to the Knesset but hopefully we'll still add it...
