### ISSUE TITLE
How to get feedback on content to add / remove from non-git users

### ISSUE THREAD

**Issue by 4tal** [4tals/LinksForIsrael#13]

**Comment by liranprof** [comment]
To gather feedback on content from non-git users (assuming you mean people who are not familiar with version control systems like Git), you can follow these steps:

1. Identify Your Target Audience:
   Determine who your non-Git users are and what their background is. This will help you tailor your approach and content to their needs and preferences.

2. Share Your Content:
   Make your content accessible to your target audience. This might involve sharing it via email, on a website, through a file-sharing platform, or in a document.

3. Create a Feedback Survey or Form:
   Develop a simple feedback survey or form using tools like Google Forms, SurveyMonkey, or Typeform. Include questions that are easy for non-technical users to answer, such as:
   - What parts of the content did you find helpful?
   - Were there any sections that were confusing or unclear?
   - Is there any additional information you would like to see included?
   - Do you have any suggestions for improvement?

4. Share the Feedback Form:
   Share the feedback form along with the content. Encourage users to provide their thoughts, opinions, and suggestions.

5. Provide Clear Instructions:
   Ensure that your instructions for using the feedback form are straightforward and easy to follow. Include a deadline for submitting feedback if applicable.

6. Collect and Analyze Feedback:
   Gather the feedback received from your non-Git users. Pay attention to common themes or issues that arise in their responses.

7. Act on Feedback:
   Use the feedback to make improvements to your content. Add or remove sections as suggested, clarify confusing parts, and incorporate any valuable insights.

8. Follow Up:
   If possible, follow up with the users who provided feedback to let them know how their input was used to improve the content. This can encourage continued engagement and feedback in the future.

9. Iterate:
   Continue to refine your content based on ongoing feedback to ensure it remains relevant and valuable to your non-Git users.

By following these steps, you can effectively gather feedback from non-Git users and make informed decisions about what to add or remove from your content to better meet their needs.

**Comment by liranprof** [comment]
Answer from chatgpt

**Comment by ohadschn** [comment]
@4tal Do you mean "non git" or "non github"?
In case of the former, I believe it's covered in https://github.com/4tal/ConnectPortal/issues/22

**Comment by 4tal** [comment]
I guess we did it via forms and apps script
