### ISSUE TITLE
Disabling Hamas users: https://t.me/hofchim

### ISSUE THREAD

**Issue by ohadschn** [4tals/LinksForIsrael#151]
verified - my sister is there from day one

סוגרים להם יוזר!
בואו לקחת חלק במאבק להפסקת הפייק והרוע של החמאס.
הצטרפות לקבוצת הטלגרם בקליק אחד ודיווח על כל מי שמפיץ שנאה ורוע מהצד השני.
מאז הקמת הקבוצה נסגרו מאות יוזרים רעילים של החמאס שמפיצים בכל העולם תעמולת חמאס שטנית. 
להצטרפות לקבוצת הטלגרם

**Comment by 4tal** [comment]
Done
