### ISSUE TITLE
Enforce HTTPS

### ISSUE THREAD

**Issue by ohadschn** [4tals/LinksForIsrael#153]
https://docs.github.com/en/pages/getting-started-with-github-pages/securing-your-github-pages-site-with-https#enforcing-https-for-your-github-pages-site

This is currently not enforced:
![image](https://github.com/4tal/LinksForIsrael/assets/8555641/f742ae6e-7c71-4f45-96c7-19c169a16eff)

**Comment by RobiFerentz** [comment]
Opened a PR. Not sure if there's a server side way to do it with github pages, so implemented a simple redirect on the client.

**Comment by 4tal** [comment]
Can you please handle case of localhost. Currently it breaks local development

**Comment by ohadschn** [comment]
This is redundant, less secure (e.g. browser extension can interfere/block the redirection JS), and can cause issues (e.g. localhost).

There is a way to do it from the server side, which I linked above: https://docs.github.com/en/pages/getting-started-with-github-pages/securing-your-github-pages-site-with-https#enforcing-https-for-your-github-pages-site

@4tal must be performed by admin, and then I suggest reverting this PR.

**Comment by ohadschn** [comment]
@4tal following our chat, here's what you should do:
1. Uncheck "Enforce HTTPS" at the GitHub pages config (https://docs.github.com/en/pages/getting-started-with-github-pages/securing-your-github-pages-site-with-https#enforcing-https-for-your-github-pages-site)
2. Enable Always HTTPS at the Cloudflare level (https://developers.cloudflare.com/ssl/edge-certificates/additional-options/always-use-https/#encrypt-all-visitor-traffic): `SSL/TLS` > `Edge Certificates` > `Always Use HTTPS`

**Comment by ohadschn** [comment]
@4tal ping - this should be really simple

**Comment by 4tal** [comment]
Done

**Comment by ohadschn** [comment]
Now we're talking:
```
> curl http://www.linksforisrael.com -v
*   Trying 76.76.21.9:80...
* Connected to www.linksforisrael.com (76.76.21.9) port 80 (#0)
> GET / HTTP/1.1
> Host: www.linksforisrael.com
> User-Agent: curl/8.0.1
> Accept: */*
>
* HTTP 1.0, assume close after body
< HTTP/1.0 308 Permanent Redirect
< Content-Type: text/plain
< Location: https://www.linksforisrael.com/
< Refresh: 0;url=https://www.linksforisrael.com/
< server: Vercel
<
Redirecting...
```
