### ISSUE TITLE
Add the unofficial battle call of the war: Flip on them, better them

### ISSUE THREAD

**Issue by ohadschn** [4tals/LinksForIsrael#160]
I think it would be a nice gesture, maybe at the bottom of the page after all the links
https://twitter.com/kann/status/1712897481837539810?t=kxXrXgX59tp1yPnrYiS4Iw&s=19
![image](https://github.com/4tal/LinksForIsrael/assets/8555641/dc897827-8b49-459e-b9d0-bf46aac57f98)

**Comment by 4tal** [comment]
<img width="1115" alt="image" src="https://github.com/4tal/LinksForIsrael/assets/6404507/1e95eb32-5a65-4b72-b832-9730d22d1915">

**Comment by ohadschn** [comment]
Can we make the icon a little larger??
You can barely make out Rachels cookies!
