### ISSUE TITLE
Family hosting: Hug the south with love

### ISSUE THREAD

**Issue by ohadschn** [4tals/LinksForIsrael#161]
https://docs.google.com/forms/d/e/1FAIpQLSd7gX9K82fDyiGDloR3UmFmKxmCX8TvkcAs6Tezil-OPW9CfQ/viewform?pli=1&pli=1

**Comment by 4tal** [comment]
Simple form with no feedback

**Comment by ohadschn** [comment]
> https://docs.google.com/forms/d/e/1FAIpQLSd7gX9K82fDyiGDloR3UmFmKxmCX8TvkcAs6Tezil-OPW9CfQ

I think we should keep such issues open and just add something like `validation-needed` tag (reclose if you disagree).
This could be an important initiative, we just need to invest a little to find out.

**Comment by ohadschn** [comment]
Form is closed
