### ISSUE TITLE
[NEW-INITIATIVE]: מארחים ומתארחים

### ISSUE THREAD

**Issue by ohadschn** [4tals/LinksForIsrael#168]
### Initiative Name
HostersAndGuests

### Initiative Description
חיבור בין משפחות מהדרום למשפחות מארחות

### Initiative Details
המיזם בהתנדבות מלאה.
כל המידע באתר נשמר לצורך קישור בין משפחות שמחפשות לארח, ומשפחות שמחפשות להתארח, ולמטרה זו בלבד.
המידע לעולם לא יועבר לאף גוף צד שלישי.

### Initiative Validation Details
I talked to the owner (video chat), it's legit.

### Initiative Category
FamilyHosting/Main

### Initiative main URL
https://findhosts.co/

### Initiative Website
https://findhosts.co/

**Comment by 4tal** [comment]
missing reference or if project actually functions

**Comment by 4tal** [comment]
reOpen it if you think it's relevant.

**Comment by ohadschn** [comment]
> missing reference or if project actually functions

I totally agree, but this is why we have our verification process :)
In this case, I think I found the owner and shot him a question, will update
