### ISSUE TITLE
Split links JSON into multiple JSON

### ISSUE THREAD

**Issue by ohadschn** [4tals/LinksForIsrael#186]
The links JSON is already 800 lines long.
As we accrue more and more categories and link, it will become unruly.
I suggest we split to folders per category, and in each folder split to sub-categories. 

Something like:
* `/_data/links.json` (if we ever want top-level (no category) links
*  `/_data/mentalHealth/links.json` (if we ever want top-level (no category) links
* `/_data/mentalHealth/psychology/links.json` (if we ever want top-level (no category) links

We can always combine them to one large JSON in the CI (if it makes Jekyll templating easier / requires less changes).

**Comment by chiptus** [comment]
related https://jekyllrb.com/docs/datafiles/#subfolders

**Comment by chiptus** [comment]
I was just testing, and I'm almost done :)

**Comment by 4tal** [comment]
#188

**Comment by ohadschn** [comment]
let's keep this open, maybe I'll try to make the subcategory separation + order fix

**Comment by 4tal** [comment]
@ohadschn Order fixed using the meta json

**Comment by ohadschn** [comment]
> @ohadschn Order fixed using the meta json

Cool, I suspect sub-categories can be done in a similar fashion (point to them from the parent category JSON)

**Comment by ohadschn** [comment]
My suspicion has been confirmed: https://github.com/4tals/LinksForIsrael/pull/226
