### ISSUE TITLE
Add logo / favicon for initiatives

### ISSUE THREAD

**Issue by ohadschn** [4tals/LinksForIsrael#189]

**Comment by Anatolysco** [comment]
Favicons:
![favicon](https://github.com/4tals/LinksForIsrael/assets/12582720/8359d128-e9bb-42c7-b4bc-3053092c211a)
![favicon](https://github.com/4tals/LinksForIsrael/assets/12582720/c9c7afab-92c7-408b-b505-df6449381afb)

**Comment by ohadschn** [comment]
@4tal isn't this already done (`initiativeImage`)?

**Comment by 4tal** [comment]
Done
