### ISSUE TITLE
Add Descriptions: Provide clear and concise descriptions for each initiative in the repository

### ISSUE THREAD

**Issue by 4tal** [4tals/LinksForIsrael#19]
If you want to update description of an item or a list. comment here with the specific area you want to update and we'll open new issue to be more granular

**Comment by ohadschn** [comment]
@4tal all descriptions should be folder by default. Currently some descriptions are taking up expensive real estate. For example:
![image](https://github.com/4tal/ConnectPortal/assets/8555641/9238d781-bd4e-48f1-8f90-421fbf8697e2)

**Comment by ohadschn** [comment]
Maybe the descriptions could just be hovers?

**Comment by galbit** [comment]
Verified links - Make sure to show that the links are verified maybe with a symbol (everything is verified, but the user needs to feel it)

**Comment by 4tal** [comment]
Not well defined.

**Comment by ohadschn** [comment]
> Not well defined.

OK, then how about: 
provide **any** description for each initiative in the repository

Because right now some initiatives don't have any description at all...

**Comment by 4tal** [comment]
I'm not a fan of too high level tasks. Not sure, what to do about it.

**Comment by ohadschn** [comment]
> I'm not a fan of too high level tasks. Not sure, what to do about it.

Don't we have a content team? We can start with something simple like:
1. Go over all JSONs
2. Whenever the `description` property is empty, populate is with a short and concise description

WDYT?

**Comment by 4tal** [comment]
Not priority rn
