### ISSUE TITLE
Solve theme issue in local serving

### ISSUE THREAD

**Issue by bergden-resonai** [4tals/LinksForIsrael#193]
@4tal Can you please elaborate on this issue?
![image](https://github.com/4tal/LinksForIsrael/assets/37291459/fbd23899-03ec-4f65-9d9e-cdc8183b0831)

This is what I see locally and it seems identical to the online version (Mac, Chrome)
![image](https://github.com/4tal/LinksForIsrael/assets/37291459/3fdb6175-1d57-40c9-96db-06e2937fe878)

**Comment by bergden-resonai** [comment]
Maybe this is the issue?
![image](https://github.com/4tal/LinksForIsrael/assets/37291459/0f94f78c-7812-486c-a119-11fa20711ebd)

I can't see how this is affecting anything

**Comment by chiptus** [comment]
I think https://github.com/4tal/LinksForIsrael/pull/187 fixed it, I've seen it once, but not after removing the double entry for github pages

**Comment by 4tal** [comment]
Seems fine.
