### ISSUE TITLE
Add News & Information Sources Category

### ISSUE THREAD

**Issue by 4tal** [4tals/LinksForIsrael#203]
Then, Update the following Link: https://t.me/+1TjNKRq-xxxkNjYx היי מוזמנים להכנס קבוצת טלגרם שלוקחת מידע מכמה ערוצי טלגרם ומתרגמת לעברים ערוצים כמו gazenow ועוד

**Comment by ohadschn** [comment]
@4tal do we still want this?

**Comment by 4tal** [comment]
Idk, it's a General question

**Comment by ohadschn** [comment]
@4tal let's ask it like this - how is a news & info category specific to iron swords?
If it's not, and we're just going to link to various news platforms, I think we can drop it...

**Comment by ohadschn** [comment]
@4tal until we decide, could you perhaps convert this to a discussion (close this issue)?

**Comment by 4tal** [comment]
Agree
