### ISSUE TITLE
Put all CSS in an organized nested manner

### ISSUE THREAD

**Issue by bergden-resonai** [4tals/LinksForIsrael#205]
Follow-up to here:
https://github.com/4tal/LinksForIsrael/pull/195

Some classes are not nested correctly (or at all) in the CSS causing the theme to take priority in some cases and making it harder to navigate and edit the CSS

**Comment by 4tal** [comment]
@bergden-resonai Can you make this issue more specific or this is specific as can get?

**Comment by bergden-resonai** [comment]
Probably best to wait for the new design with this
Hopefully the new code will use more separate components, and then organizing the css will be easier

But overall can't be more specific
We just need to make sure all classes are defined once and in the correct place

**Comment by 4tal** [comment]
Sounds Good.
