### ISSUE TITLE
Search Results Behaviour

### ISSUE THREAD

**Issue by bergden-resonai** [4tals/LinksForIsrael#207]
Previous Title: Getting to a link from the search results should highlight the specific link - not just the category

Current behavior: I search for some general cause, click "take me there" on a result, it opens the category the link belongs to (this list might be long and I don't see my actual search result anymore)

I suggest we support URLs to the specific link (i.e `linksforisrael.com/#Donations/DonateToFamilies`) and highlight the specific link

Another option is to start having a "link page" - a dedicated page for each link with just that link's information and maybe pointers to "relevant causes"

**Comment by 4tal** [comment]
We need UXUI Input in here

**Comment by ohadschn** [comment]
@4tal / @bergden-resonai is this still relevant?

**Comment by bergden-resonai** [comment]
IMO the search is an important feature and current experience is not great (not on mobile and definitely not on desktop)

**Comment by ohadschn** [comment]
@omer-friedman I assume your search work will resolve this?
