### ISSUE TITLE
Add yet another family hosting matcher: https://safe-bed.info

### ISSUE THREAD

**Issue by ohadschn** [4tals/LinksForIsrael#208]
בעקבות המצב אנחנו ראינו המון פרסומים של אנשים טובים עם לב ענק ❤שמעוניינים לארח ומקומות לתושבי הדרום , לכן החלטנו להרים את הכפפה ולהקים אתר שיסכם את כל המודעות בצורה מסודרת וקלה . 

הכנסו ומלאו את הפרטים ורק ביחד ננצח 🇮🇱

https://safe-bed.info

**Comment by 4tal** [comment]
Done
