### ISSUE TITLE
Add IsraelGives life saving equipment form: https://docs.google.com/forms/d/e/1FAIpQLSeB2Ws2_21qvwhfb1aFDhTB0DQSsuyFL4jRIBoSYFHQV7P7xQ/viewform

### ISSUE THREAD

**Issue by ohadschn** [4tals/LinksForIsrael#211]
אנחנו המטה המשותף לציוד לחיילים ישראל-ארהב.
עובדים בשיתוף עם IEA-Israel emergency aid ו ISRAEL-GIVES, למטרת מימון חסרים של ציוד מציל חיים לכוחות בגבול ולתשובים בעוטף.

כתבו בטופס איזה ציוד חסר לכם וציינו כמויות מדוייקות

עוד עלינו
https://www.israelemergencyaid.com/

**Comment by 4tal** [comment]
Done
