### ISSUE TITLE
Add Yedidim - fixing shelters etc

### ISSUE THREAD

**Issue by ohadschn** [4tals/LinksForIsrael#214]
https://yedidim-il.org/%D7%99%D7%93%D7%99%D7%93%D7%99%D7%9D-%D7%9E%D7%AA%D7%92%D7%99%D7%99%D7%A1%D7%99%D7%9D-%D7%9C%D7%9E%D7%9C%D7%97%D7%9E%D7%AA-%D7%97%D7%A8%D7%91%D7%95%D7%AA-%D7%91%D7%A8%D7%96%D7%9C/

**Comment by 4tal** [comment]
![Image](https://github.com/4tals/LinksForIsrael/assets/6404507/8305b98f-2e0e-4e3e-b2d6-80e9e9c0c6ab)
