### ISSUE TITLE
[NEW-INITIATIVE]: סיוע נפשי קבוצתי או פרטני בשיטת EMDR

### ISSUE THREAD

**Issue by ohadschn** [4tals/LinksForIsrael#215]
### Initiative Name
התערבות פסיכולוגית - אסון רעים

### Initiative Description
סיוע נפשי קבוצתי או פרטני ע״י מטפלים מומחים לטראומות בשיטת EMDR

### Initiative Details
אנשים רבים מנשוא חוו בימים האחרונים אירועים קשים מאוד. כאשר אדם חווה חוויה טראומתית, הזיכרון של האירוע הטראומטי נשאר "קפוא בזמן" יחד עם הקולות, הריחות, הרגשות והתחושות. כל היזכרות יזומה או לא מתוכננת נחווית כקשה, כאילו האדם מתנסה בטראומה שוב בהווה.
 הוא יסבול לעיתים קרובות מסימפטומים שונים, מתגובות רגשיות חזקות, מהתנהגויות לא מתאימות, מתפיסה עצמית שלילית, ועשוי אף להימנע מאזורים ואירועים הנקשרים לזיכרון והגורמים לעוררות, לעיתים מבלי שיהיה מודע לכך.
שיטת EMDR היא שיטה טיפולית מוכחת מדעית לטיפול בנפגעי חרדה וטראומה. מטפלי עמותת EMDR -  פסיכולוגים ועו״סים מוסמכים, התנדבו  לספק תמיכה וסיוע נפשי ראשוני לעיבוד הטראומה לנפגעי מלחמת ׳חרבות ברזל׳ בין באופן קבוצתי או פרטני.

### Initiative Validation Details
Reputable source: https://regishut.co.il/%D7%A8%D7%95%D7%95%D7%97%D7%94/%D7%9E%D7%99%D7%96%D7%9D-%D7%AA%D7%9E%D7%99%D7%9B%D7%94-%D7%A0%D7%A4%D7%A9%D7%99%D7%AA-%D7%9C%D7%A0%D7%9E%D7%9C%D7%98%D7%99-%D7%94%D7%9E%D7%A1%D7%99%D7%91%D7%94/

### Initiative Category
MentalSupport/Main

### Initiative main URL
[No response](https://docs.google.com/forms/d/e/1FAIpQLSfugXCKAYd3DhnAECYgo2sR0vpF2qZG-Wc4tsDNGCy4kylY5w/viewform)

### Initiative Form
https://docs.google.com/forms/d/e/1FAIpQLSfugXCKAYd3DhnAECYgo2sR0vpF2qZG-Wc4tsDNGCy4kylY5w/viewform

**Comment by 4tal** [comment]
I don't think only form format is good or something we need to add

**Comment by ohadschn** [comment]
> I don't think only form format is good or something we need to add

Why?
I think the main factor should be the size/impact of the initiative, not its form (website / whatsapp group / form)
Recall for example this form, behind which stand huge organizations: (the soldier association etc,) https://forms.monday.com/forms/25c5ac9f7676f6ffbf7fae7b982e87ef?r=use1
