### ISSUE TITLE
Add "Brothers to the barn" farmer support initiative: https://www.onkaiten.com/donations/israel/rishlakish

### ISSUE THREAD

**Issue by ohadschn** [4tals/LinksForIsrael#219]
שלום, ימים קשים כלכך קשים. מתוך הכאב הבלתי נסבל מנסים ליצור תנועה של שינוי, נחמה של הטוב.

כבר שבוע שאנחנו כאן בריש לקיש מבינים את המקום שלנו לעזרה ומרפא!
יחד עם השף יניב גור אריה, נעמה שטרנליכט, סהר שמעון מעמותה לקידום חקלאות מחדשת, עמותה לקידום חקלאות אורגנית, האירגון האורגני, ד״ר אורי מאיר ציזיק,אסף אביר,טל סורסקי ורבים אחרים.

לפרוייקט קראנו ״מאדמה לאדם״ 
מתוך הבנה עצובה
שצפויה לנו תקופה 
של מחסור בתוצרת חקלאית ישראלית
ומוצרי מדף שונים.
שישנם מקומות רבים,
שניתן להציל מזון מזין ולהביא למי שזקוק. 

למצוא דרכים לתמוך בחקלאים!וליצור חיבורים חדשים ולחזק קיימים. 
הבנה שאנחנו האזרחים /ספקי המזון לא יכולים לאורך זמן להמשיך ולשאת כספית את הזנת הצבא ושיש לעשות סדר בחלוקת המשאבים שלנו. 

התחלנו ליצור קשר עם מאות חקלאים ללקט ולשנע תוצרת חקלאית עודפת או סוג ב׳ - שלא ניתן למכור. 
בבית הבד פתחנו מרכז לוגיסטי אליו מגיעים בצהרים עשרות תלמידי תיכון מהאזור יחד עם מתנדבים בוגרים ממיינים ומאחסנים במשאית קירור את התוצרת שאספנו.
עשרות נהגים הגיעו בדרכם לצפון וממלאים את הרכב בפירות ועוגות (מהפירות סוג ג׳)
פרוייקטים של הזנה שעובדים בצפון, תל אביב וירושלים מקבלים באופן רציף את כל התוצרת שהצלחנו להציל. 

במקביל הקמנו  צוות שפים ואנשי מקצוע, בהובלת יהלומה לוי ואפרת זוהר לבניית  תוכנית ארוכת טווח שתעסוק בתחום האוכל כמרפא. וכן מפגשים עם הקהילות שנפגעו ואנשי הקולינריה שלנו להרצאות וסדנאות אוכל. 

לפרטים נוספים 
נשמח לעדכן 
פתחנו דף תרומות ברעיון לשלוח לחו״ל  לחברים ומשפחה שרוצה לתמוך בקהילות שנפגעו ולהציל את המזון בישראל (מי שמקבל בחו״ל נפתח באנגלית).

נודה אם תפיצו הלאה

**Comment by 4tal** [comment]
Done
