### ISSUE TITLE
Add Zapier Automation from Google Forms to Github Issues

### ISSUE THREAD

**Issue by 4tal** [4tals/LinksForIsrael#22]

**Comment by ohadschn** [comment]
@4tal have you murdered and also inherited???
You add an external system (GForms), and now you want to add another (Zapier) in hopes that 2 wrongs would make a right? 😉

I strongly suggest we use GitHub issue templates (which should be pretty much equivalent to GForms) and then hook a GitHub action on them: https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#issues

**Comment by ohadschn** [comment]
@4tal I saw in the chat you proposed some ChatGPT for this, I would really try to avoid it and simple have the category in the form (let the submitter select it). I also agree with Miki (I'm guessing @mimafogeus2) about keeping the markdown structured, we will need at least some structure for automatic PRs to make sense.

**Comment by 4tal** [comment]
@ohadschn Got his Github Templates

**Comment by ohadschn** [comment]
Are you sure you want to close this? It would mean directing people directly to GitHub to open an issue, where most people won't even have a user (which is mandatory for issue submission)

It would constitute a tradeoff, less work for us but we might lose on some suggestions from users who couldn't be bothered with registration...

**Comment by ohadschn** [comment]
@4tal any luck with this automation?

**Comment by ohadschn** [comment]
Closing in favor of https://github.com/4tals/LinksForIsrael/issues/393
