### ISSUE TITLE
Add "Iron Likes" public diplomacy for social media initiative: https://ironlikes.com

### ISSUE THREAD

**Issue by IronLikes** [4tals/LinksForIsrael#221]
https://ironlikes.com/

**Iron Likes - Blasting Twitter with pro-Israeli likes!**
The initiative is a website and Chrome extension which helps users to multiply their pro-Israeli likes on Twitter.

The website automatically “likes” tweets that support Israel, i.e., a single user can make thousands of likes without even sitting at the computer!
The tweets are carefully selected from Twitter by a small team of high quality volunteers.
“Likes” are the fastest and most efficient way to spread on Twitter, so that via wide distribution, this instrument can significantly influence the sharing of pro-Israeli materials on the web.

**Together we will prevail!💪🏻**

**Comment by ohadschn** [comment]
@IronLikes looks like you're a developer, any chance for a PR?
It's really simple, just add your site to the relevant JSON under `_data/links` :)

**Comment by IronLikes** [comment]
Done https://github.com/4tals/LinksForIsrael/pull/223

**Comment by ohadschn** [comment]
@IronLikes could you please help us with validation?
If you'd like, we could make a quick video call (you can contact me directly via the e-mail in my GitHub profile)

**Comment by ohadschn** [comment]
@4tal FYI I made a short video call with the owner to validate
