### ISSUE TITLE
Normalize (sub)category names

### ISSUE THREAD

**Issue by ohadschn** [4tals/LinksForIsrael#227]
At least 4 different conventions:
* "volunteering"
* "tech-initiatives"
* "EquipmentNFood"
* "NEedarim"

**Comment by 4tal** [comment]
I suggest:
1. CamelCase.
2. Has Clear meaning and related to category

It should be in the URL so we can provide information using clear (Sub)Category names.

**Comment by ohadschn** [comment]
> I suggest:
> 
> 1. CamelCase.
> 2. Has Clear meaning and related to category
> 
> It should be in the URL so we can provide information using clear (Sub)Category names.

I would add to this list 
3. English (e.g. `MissingPersons` rather than `Needarim`)
