### ISSUE TITLE
Add site availability/uptime tests (e.g. pingdom)

### ISSUE THREAD

**Issue by ohadschn** [4tals/LinksForIsrael#230]
Perhaps we could do this as part of https://github.com/4tals/LinksForIsrael/issues/272

**Comment by 4tal** [comment]
sounds good

**Comment by ohadschn** [comment]
Enabled on my Azure Monitor / Application Insights account, added both myself and @4tal:
![image](https://github.com/4tals/LinksForIsrael/assets/8555641/ad9f19ce-58e1-43a4-a1ce-e169911e20a1)

Upon failure we should get an email that looks like this:
![image](https://github.com/4tals/LinksForIsrael/assets/8555641/22a35a5f-f3cb-471e-b337-c49790558396)

**Comment by 4tal** [comment]
Pagaz
