### ISSUE TITLE
Add Memorial Drawings

### ISSUE THREAD

**Issue by 4tal** [4tals/LinksForIsrael#237]
שלום חברים.
בימים האחרונים אני יושב ומאייר את דמותם של הנופלים שהיו שם בשבילנו. הורים, צעירים וצעירות ששילמו בחייהם כדי להגן עלינו. זה עוזר לי לעצור, להסתכל להם בעיניים, לחשוב על המשפחות שלהם ועל החברים שלהם, ולכאוב את הכאב שלהם. אם אתם יודעים על משפחה שעשויה לרצות את הציור של יקירם, ניתן לפנות אלי במייל. שלא נדע עוד צער יותר ממה שידענו כבר. בנצי. Benziwolman@gmail.com

This is pending for  #236

**Comment by 4tal** [comment]
`אולי כדאי לפנות אליו במייל לשאול האם הוא רוצה שנשתף את המייל שלו בלינקפורישראל. מה דעתכם?`

**Comment by ohadschn** [comment]
> `אולי כדאי לפנות אליו במייל לשאול האם הוא רוצה שנשתף את המייל שלו בלינקפורישראל. מה דעתכם?
It's probably best if he built a simple form (e.g. Google/Microsoft/Monday)

**Comment by 4tal** [comment]
Added with Simple Email
