### ISSUE TITLE
Add Decentralized Hamal Tech Initiative  https://chat.whatsapp.com/EHzZvrsKP0YARKHQqg5KdG

### ISSUE THREAD

**Issue by 4tal** [4tals/LinksForIsrael#24]
היי חברים,
מיזם נוסף.
כבר פותח קבוצה!

הצורך: הצלת חיים של אזרחים במקרה של מתקפת טרור על בתיהם.
השיטה: מערכת שו"ב קיימת שתעבור בדיקות והתאמות.
המערכת מיועדת לתרחישים של massive shooters אבל ניתן בקלות להתאים אותה לתרחישים של חמ"ל מקומי/עירוני/גזרתי
אנחנו יוצאים מתוך נקודת הנחה שהפתרונות של פיקוד העורף ומדא לא רלוונטים מספיק ונדרשת גישה יותר ביזורית ומקומית.

כרגע אנחנו צריכים את המשאבים הבאים:
1.בדיקות תוכנה
2. בדיקות חדירות
3. הוספת פונקציונליות של MFA לניהול המערכת
4. כותבי תו"ל
5. כותבי מדריך הפעלה למתאר השימוש שלנו
6. מפעלי חמ"לים או תומכי מפעלי חמ"לים מקומים

מי שעונה על אחת הדרישות/הבקשות בבקשה לדבר איתי ולהצטרף לקבוצה

**Comment by ohadschn** [comment]
This is just a call to action, I'm not sure if this thing even exists...
Asked to join the group, but for now closing
