### ISSUE TITLE
[NEW-INITIATIVE]: Safe Place (מקום בטוח)

### ISSUE THREAD

**Issue by ohadschn** [4tals/LinksForIsrael#244]
### Initiative Name

Safe Place

### Initiative Description

פלטפורמה המשדכת בין אזרחים שמעוניינים לארח ותושבים מפונים המחפשים אירוח

### Initiative Details

עם המשך הלחימה במסגרת [מלחמת "חרבות ברזל"](https://www.israelhayom.co.il/news/defense/article/14710168), ממשיך גם פינוי התושבים מעוטף עזה, כאשר לפי פיקוד העורף, ככל הנראה יורחב מעגל המפונים בתקופה הקרובה. בעוד שרבים מתושבי העוטף שפונו נמצאים כרגע בבתי מלון, הגדלת היקף המפונים צפויה לגרום למחסור במלאי חדרי המלון ברחבי הארץ, המוערכים כרגע ב-50 אלף חדרים.

על מנת למנוע מצב שבו משפחות נאלצות לחיות במקלטים, פותחה אפליקציית "מקום בטוח" שמטרתה לסייע בפינוי תושבים משטחי ירי מוגבר. היוזמה מאפשרת לאזרחים למצוא מקום לשהות בו ברחבי הארץ אצל מארחים נדיבים - אנשים פרטיים, ארגונים, חברות ועוד.

באמצעות האפליקציה, ניתן יהיה כאמור להרחיב את היקף מקומות האירוח בארץ ולספק מענה לכמות גדולה יותר של מפונים. מאחורי הפיתוח עומדים צוות של מתנדבים האחראים על תפעולה ובדיקת אמינות האנשים שנרשמים בה, בשיתוף פעולה עם חברת סטארטאפ ישראלית שבנתה ומתחזקת את הצד הטכנולוגי.

ניתן להירשם באפליקציה גם כאורח וגם כמארח ולחפש מקום אירוח, ממש כמו חיפוש דירה. תוכלו לבחור במקום לפי סינונים כמו מיקום גיאוגרפי, כמות האנשים בקבוצה המחפשים מקום, סוג המיגון הקיים, האם המקום כשר, האם הוא ידידותי לבעלי חיים, לבקש לראות צילום של המקום וכו'.

לדברי אחד מיזמי הפרויקט, שביקש לא להזדהות: "ראינו שכל העשייה החשובה של מציאת מקום לינה עבור תושבי העוטף מנוהלת בטבלאות אקסל באופן ידני או בקבוצות ווטסאפ, מה שמקשה על מציאת פתרון ומאט מאוד את קצב הטיפול. יש לנו בחברה את הידע כדי לייצר פתרון כזה, אז הרמנו את הכפפה לבנות את האפליקציה ולשתף פעולה עם צוות מתנדבים מדהים".

### Initiative Category

FamilyHosting

### Initiative Website

https://safe-zone.spiritt.app/

**Comment by 4tal** [comment]
Done

![Image](https://github.com/4tals/LinksForIsrael/assets/6404507/107e7fb4-2fde-472d-b29d-8910d067f873)

**Comment by ohadschn** [comment]
> Done
> 
> ![Image](https://user-images.githubusercontent.com/6404507/277062406-107e7fb4-2fde-472d-b29d-8910d067f873.png)

Man we gotta do something about those long descriptions!
