### ISSUE TITLE
[NEW-INITIATIVE]: Hug Into the night (חיבוק לתוך הלילה)

### ISSUE THREAD

**Issue by ohadschn** [4tals/LinksForIsrael#248]
### Initiative Name

Hug Into the Night

### Initiative Description

מיזם מהעורף האוסטרלי - מוזמנות לשתף למי שלא מצליחה להרדם... 

### Initiative Details

לא מצליח.ה לישון?
האחיות האוסטרליות שלך כאן בשבילך
חברנו יחד כמה מנחות ומטפלות ישראליות שגרות באוסטרליה למיזם ״חיבוק לתוך הלילה״ - לתת עזרה למי שבישראל בשעות שהן הכי קשות להרבה מאיתנו - שעות הלילה.
הזום שלנו פתוח מ23:00 עד 2:00 בלילה של ישראל.
אם קשה לך לישון, אנחנו נהיה שם איתך לנשימה משותפת, שיתוף ואוורור רגשי, מרחב בטוח לביטוי ויחד.
אל תשארו לבד עם נדודי השינה.
בואו 🩷
קישור לקבוצת ווצאפ שבה נשלח את הקישורים והתזכורות  

### Initiative Validation Details

Source: Forwarded many times on WhatsApp
Link to reputable source(s) promoting the initiative: https://www.facebook.com/groups/secrettelaviv/posts/10160868332050943/
Contact details for members of the initiative's team (so we can contact them directly for validation): https://www.facebook.com/groups/327483250942/user/602955301
The WhatsApp group (link below) contains ~950 members, so pretty sure it's legit.

### Initiative Category

MentalSupport

### Initiative Website

https://chat.whatsapp.com/K7k9bNxAkTR398D034BiC8

**Comment by 4tal** [comment]
<img width="625" alt="image" src="https://github.com/4tals/LinksForIsrael/assets/6404507/1dac684b-e738-4d25-8c0b-80d89fad5163">
