### ISSUE TITLE
Read More about initiatives on click, hover or else:

### ISSUE THREAD

**Issue by 4tal** [4tals/LinksForIsrael#251]
To Avoid display like:

![Image](https://github.com/4tals/LinksForIsrael/assets/6404507/20ce4015-d3d2-4244-8864-c728c44dcdbb)

**Comment by ohadschn** [comment]
@4tal it looks like the feature is broken, I don't see any way to expand the description:
![image](https://github.com/4tals/LinksForIsrael/assets/8555641/37d7486f-da48-49c8-ae11-a47057b469e2)

**Comment by 4tal** [comment]
It's not broken, content on git:
![Image](https://github.com/4tals/LinksForIsrael/assets/6404507/ac9f7f6d-ec56-4215-b609-58524cb63c77)

**Comment by 4tal** [comment]
Closed and added fix content for https://github.com/orgs/4tals/projects/1/views/5?pane=issue&itemId=44202732
