### ISSUE TITLE
[NEW-INITIATIVE]: Winning Together מנצחים ביחד

### ISSUE THREAD

**Issue by ohadschn** [4tals/LinksForIsrael#255]
### Initiative Name

Winning Together

### Initiative Description

Aggregator of initiatives (similar to our website)

### Initiative Details

אנחנו קהילת BNF הקמנו עמוד המרכז את כל ארגוני הסיוע והתנדבות במקום אחד,

### Initiative Validation Details

Source: WhatsApp group תומכים מהבית - סיוע למשפחות מילואימניקים
Link to reputable source(s) promoting the initiative: https://t.me/s/yairsherkinews 
Contact details for members of the initiative's team (so we can contact them directly for validation): `~itzik` (from above WhatsApp group, phone number redacted for privacy)

### Initiative Category

InitiativesAggregation/Aggregation

### Initiative Website

https://www.bnf.co.il/stay-together/

**Comment by 4tal** [comment]
Done
