### ISSUE TITLE
[NEW-INITIATIVE]: LinkedIn Publicity הסברה בלינקדאין

### ISSUE THREAD

**Issue by ohadschn** [4tals/LinksForIsrael#256]
### Initiative Name

LinkedIn Publicity 

### Initiative Description

Publicity on LinkedIn

### Initiative Details

קול קורא: בואו תעזרו לנו בהסברה בלינקדאין 🔵
אנחנו קבוצה מאורגנת של משפיענים בלינקדאין, שתאפשר להגדיל חשיפה, חידוד מסרים בזמן אמת, דיווחים על פרופילים, לייקים לפוסטים ועוד

אנחנו פועלים בכמה מישורים:
>> עזרה בכם בתור כלי הפצה, לא משנה כמה עוקבים יש לכם
>> יצירת קבוצת שגרירים עם פרופילים אטרקטיביים מחו״ל שנפרסם דרכם תכנים
>> חמ״ל שמגיב על אירועים חדשותיים בזמן אמת, כתיבת תוכן, שימוש ב AI ככלי עזר, תכנות, שיווק, כל מה שצריך יש לנו פה מומחים להכל

נשמח לעוד מכפילי כוח, לינק לקבוצה

### Initiative Validation Details

Source: Work WhatsApp group 
Contact details for members of the initiative's team (so we can contact them directly for validation): ~Daniel (from my work group, phone# redacted for privacy)
I talked to my colleague, it's an x-MS worker, verifies each new member

### Initiative Category

hasbara

### Initiative WhatsApp

https://chat.whatsapp.com/EQopAWUyRrt8IIg5M7ZvbV 

### Initiative Document

https://docs.google.com/spreadsheets/d/1z9-2aXt_CmmAOyXEhtoGO-G0HEM-2fx8MGIn3AzLRNk/edit?usp=sharing

**Comment by 4tal** [comment]
Done
