### ISSUE TITLE
[NEW-INITIATIVE]: N12 Hotline ישראל מתגייסת

### ISSUE THREAD

**Issue by ohadschn** [4tals/LinksForIsrael#260]
### Initiative Name

Israel is enlisting

### Initiative Description

 עוזרים לכל מי שזקוק לעזרה

### Initiative Details

 זקוקים לסיוע, רוצים לעזור? פנו אלינו: 050-2210169 ואנחנו נעשה את החיבור

### Initiative Validation Details

Source: https://www.instagram.com/p/Cyc7OYkAbdi/?igshid=MTc4MmM1YmI2Ng%3D%3D
Link to reputable source(s) promoting the initiative: https://www.mako-publishers.com/contact

### Initiative Category

InitiativesAggregation/AssistanceMain

### Initiative WhatsApp

https://wa.me/+972502210169

**Comment by 4tal** [comment]
Done
