### ISSUE TITLE
[NEW-INITIATIVE]: Israel Gives

### ISSUE THREAD

**Issue by ohadschn** [4tals/LinksForIsrael#268]
### Initiative Name

Israel Gives Emergency Aid

### Initiative Description

Support last mile efforts to deliver life saving equipment to Israeli soldiers and civilians on the front line.

### Initiative Details

Israel Emergency Aid is a rapid response project formed at the onset of the current war with Hamas, that is dedicated to providing immediate assistance to soldiers and civilians affected by the war.  Our mission is to collect funds to swiftly fulfill specific requests from soldiers on the front lines with Gaza and civilians in need of immediate aid.

This project operates under the auspices of [IsraelGives](https://israelgivesfund.org/), a reputable nonprofit organization that has supported over 50,000 charitable causes since its inception in 2009. 

Israel Emergency Aid is organized by a group of experienced executives, tech leaders, and law firm partners who recognized the urgent need to support soldiers lacking life saving tactical and protective gear.

### Initiative Validation Details

Source: WhatsApp group
Link to reputable source(s) promoting the initiative: https://creatorsforisrael.com/ (not sure how reputable it is, but looks legit and might be worth its own entry)
Contact details for members of the initiative's team: Scroll down to the `Who We Are` section

### Initiative Category

children

### Initiative Website

https://www.israelemergencyaid.com/

### Initiative Form

https://docs.google.com/forms/d/e/1FAIpQLSeB2Ws2_21qvwhfb1aFDhTB0DQSsuyFL4jRIBoSYFHQV7P7xQ/viewform

**Comment by 4tal** [comment]
Done
