### ISSUE TITLE
[IN PROGRESS] Automatically monitor availability of linked initiatives

### ISSUE THREAD

**Issue by ohadschn** [4tals/LinksForIsrael#272]
For example this happened to us with the previous URL of https://www.explainisrael.org/ that went down. A simple pingdom test could be a good start, we could have some automation that generates such a test for each new initiative (e.g. part of deployment).

## TODO
1. ~~Move from `axios` to `fetch`~~
2. ~~Add details in opened issue:~~
   * ~~Category~~
   * ~~Initiative name~~
   * ~~Property name~~
   * ~~Status code + Status text~~
   * ~~Exception + cause~~
3. ~~Improve parallelization (max concurrency level instead of file level).~~
4. ~~Handle transient errors~~
5. ~~Handle site blockers (list of expected 403/429)~~
6. ~~Test on fork GitHub Actions~~

**Comment by 4tal** [comment]
What about adding Green and Red visual feedback that will be fetched using ping/fetch and will help users to understand if initiative is active or not and send us feedback

**Comment by ohadschn** [comment]
> What about adding Green and Red visual feedback that will be fetched using ping/fetch and will help users to understand if initiative is active or not and send us feedback

@4tal I find it less logical in our use case - we are not some gaming server monitoring service that shows the status of some servers at any given time. The things we link to should generally always be up, and if they aren't, they should be taken down rather than create unnecessary clutter for our customers.

**Comment by 4tal** [comment]
If it will be part of deployment, it will block too much. External independent services should not affect our progress.

The developer dashboard ticket that I recently closed could have been handy to catch such feedback much faster.

**Comment by ohadschn** [comment]
> @ohadschn If it will be part of deployment, it will block too much. External independent services should not affect our progress.
> 
> The developer dashboard ticket that I recently closed could have been handy to catch such feedback much faster.

Oh, not as part of deployment - I was thinking about some scehduled/cron action (e.g. once an hour) that scans all our links, and if any are down opens an issue (or possibly even a PR). Similar to Dependabot, just for dead links.
