### ISSUE TITLE
Add "phone call" link type (<a href="tel:...>)

### ISSUE THREAD

**Issue by ohadschn** [4tals/LinksForIsrael#273]
Some initiatives simply have a phone number that you call, and we currently don't have this option (closest we have is WhatsApp).

**Comment by 4tal** [comment]
Already Supported, using link.phone

**Comment by ohadschn** [comment]
@4tal what about this one??

**Comment by ohadschn** [comment]
@4tal I see you addressed this issue here: https://github.com/4tals/LinksForIsrael/pull/384/files
However there is one piece missing - could you please add to https://github.com/4tals/LinksForIsrael/blob/main/.github/ISSUE_TEMPLATE/new_initiative.yml?
