### ISSUE TITLE
[NEW-INITIATIVE]: בקשות \ הצעות אירוח

### ISSUE THREAD

**Issue by ohadschn** [4tals/LinksForIsrael#274]
### Initiative Name

Hosting/Guest Matching

### Initiative Description

Match guests with hosts

### Initiative Details

 תודה רבה על ההתגייסות והרצון המדהים לפתוח את הבית ואת הלב לאנשים שזקוקים לכך. הבהרה חשובה - אנחנו מחברות בין אנשים שמחפשים אירוח לאנשים שמציעים אירוח ללא תשלום בלבד.

כל מי שרוצה לארח / להתארח, מוזמנים למלא את השאלון: הטופס כולל אימות, חשוב למלא את כל הפרטים!

📌 אנחנו נשלח כאן בקבוצה משפחות שמחפשות אירוח 🔵 כדי שתוכלו ליצור איתם קשר בהקדם, ומקומות פנויים לאירוח (דירות ריקות 🟢 או בקרב המשפחה 🟡)

📌 חשוב לציין כי האחראיות הינן רק הגורם המחבר ואינן מכירות באופן אישי הן את המארחים והן את המחפשים.
החיפוש והעזרה נעשית בהתנדבות מוחלטת ולכן נודה להבנתכם בעיכובים במענה ובשיבוצים.

מי שזקוק לסיוע בהסעות ניתן לפנות למנהלת הקבוצה, יש מערכי הסעות ומתנדבים מכל מקום לכל מקום בארץ 

### Initiative Validation Details

Verified by a video call with one of the admins

Form requests and offers are verified by the admins and relayed to an internal WhatsApp group for matching (where only admins can post)

### Initiative Category

FamilyHosting/Main

### Initiative WhatsApp

https://chat.whatsapp.com/JgqpxWdh9MK8BpYdDzS9hU

### Initiative Form

https://forms.monday.com/forms/2ecbc317d14d9bc50af78661e537b99d?r=euc1

**Comment by 4tal** [comment]
No visibility and way to get liveness check

**Comment by ohadschn** [comment]
I ran into them again, I see they have a second WhatsApp group already with 400+ members
Presumably the first one was full with 1000+ so together they approach 1500 people
I think this is goo enough reason to include them, IMHO visibility and livenses is **our** problem, a problem which we should not relay to our customers who could very much take advantage of this resource...
