### ISSUE TITLE
[NEW-INITIATIVE]: כיפה דיגיטלית

### ISSUE THREAD

**Issue by ohadschn** [4tals/LinksForIsrael#277]
### Initiative Name

Digital Dome

### Initiative Description

Shoot down harmful content

### Initiative Details

על מה מדווחים?
תכנים שמקדמים את הכחשת הטבח, הגחכת חטופים ונפגעים, תמיכה בטרור, שקרים ברורים ומופרכים [קראו עוד](https://digitaldome.io/#readMoreModal)

איתרתם תוכן זדוני?
הדביקו את הלינק בטופס - אנחנו נטפל בשאר

למה זה חשוב?
הרשתות החברתיות הן זירת מלחמה קריטית והן מוצפות בשקרים והסתה, תוכן זה לרוב מופץ על ידי גורמים עונים, מלבה פחד ומשבש את דעת הקהל

מי אנחנו?
התגבשנו מספר חברות הייטק ובכירים נוספים מהתעשייה לבנות פלטפורמת חמ״ל שמאפשרת מקום אחד לדווח בו על תכנים זדוניים מכל הרשתות, אימותם ודיווח שוטף וישיר לרשתות למען הסרתם

### Initiative Validation Details

Source: WhatsApp group
Link to reputable source(s) promoting the initiative: [[e.g. https://www.israelhayom.co.il/tech/tech-news/iron-swords]](https://www.calcalistech.com/ctechnews/article/syf8xofbp) 
WhatsApp group has ~450 members, X has 250 followers, looks legit

### Initiative Category

hasbara

### Initiative Website

https://digitaldome.io/

### Initiative WhatsApp

https://tinyurl.com/digitaldome

### Initiative X (Twitter)

https://twitter.com/digidomee

**Comment by 4tal** [comment]
Done
