### ISSUE TITLE
Add link for Kids games

### ISSUE THREAD

**Issue by reututy** [4tals/LinksForIsrael#279]
### Initiative Name

משחקי רוגעלך

### Initiative Description

משחקים שפותחו באהבה לילדי וילדות ישראל שמותאמים לתקופה

### Initiative Details

כ-50 מפתחים, מעצבות, אנשי סאונד, חינוך ופסיכולוגים חברו יחד כדי ליצור משחקים הסברתיים, מותאמים לתקופה, שמעודדים התנדבות, מרגיעים, משמחים ובעיקר כיפיים!

### Initiative Validation Details

https://www.games4israel.com/

### Initiative Category

children

**Comment by 4tal** [comment]
Done
