### ISSUE TITLE
Script that utilize GPT to prepare Initiative description before PR

### ISSUE THREAD

**Issue by 4tal** [4tals/LinksForIsrael#284]
Write Python Script.

Take Input string send to gpt with the following requirements:

**Comment by 4tal** [comment]
https://github.com/4tals/LinksForIsrael/blob/main/scripts/chat_gpt.py

**Comment by DanielShterenberg** [comment]
I'm on it

**Comment by DanielShterenberg** [comment]
Finished the implementation. Waiting for an approval 
https://github.com/4tals/LinksForIsrael/pull/303
