### ISSUE TITLE
[NEW-INITIATIVE]: חמ"ל היטק

### ISSUE THREAD

**Issue by ohadschn** [4tals/LinksForIsrael#286]
### Initiative Name

Hamal Hi-Tech

### Initiative Description

 חברות ההייטק מתגייסות למאמץ המלחמתי!

### Initiative Details

בצו השעה, חברות ההייטק מתגייסות לתמיכה בלחימה ובנפגעי פעולות האיבה.

בשיתוף עם עמותת ׳לב אחד׳, הקמנו מערך התנדבות וגיוס כספים בהובלת חברות Fiverr ו-HiBob. במסגרת פעילות העמותה הוקמו כבר שבעה חמ״לים הפועלים ברחבי הארץ ובניו יורק, והמתנדבים פועלים לתת מענה לצרכים הרבים העולים מהשטח ומתמקדים באספקת ציוד ומזון, ליווי משפחות ההרוגים, סיוע לנפגעים ומפונים, ביקורי פצועים בבתי החולים, תמיכה בלוחמים ובמשפחותיהם ומתן מענה ופתרון לכל מצוקה העולה מהשטח.

### Initiative Validation Details

Source: WhatsApp group, colleague is on their team
Link to reputable source(s) promoting the initiative: https://www.levechad.org/hamal-hitech-he

### Initiative Category

InitiativesAggregation/AssistanceMain

### Initiative Website

https://www.levechad.org/hamal-hitech-he

### Initiative Form

https://forms.monday.com/forms/1d979d1d97eee0324dd279c6e860eb05?r=use1

### Initiative Document

https://forms.monday.com/forms/b717ad9eb76726f28e1c3e24ef132e7e?r=use1

**Comment by 4tal** [comment]
It's Part of Lev Echad which we have in our website.
