### ISSUE TITLE
[NEW-INITIATIVE]: Medison Aid

### ISSUE THREAD

**Issue by ohadschn** [4tals/LinksForIsrael#287]
### Initiative Name

Medison Aid

### Initiative Description

מערך לוגיסטי התנדבותי לתמיכה בכוחות הבטחון ובמערך האזרחי

### Initiative Details

חמ״ל Medison Aid  - מערך לוגיסטי התנדבותי לתמיכה בכוחות הבטחון ובמערך האזרחי - קיבל מהכוחות בשטח אלפי פניות ובקשות לציידם בחליפות סערה. 

כידוע, *חליפות הסערה מגנות על החיילים שלנו מהגשם*, שומרות עליהם מהקור וכך עוזרות להם לתפקד טוב יותר בשטח. 

לשם כך, יצאנו במסע גיוס המונים לרכוש 18,000 חליפות סערה.

נשמח מאד לתרומה כדי שנוכל לעזור לכמה שיותר חיילים. 

*מחיר חליפת הסערה כ-24₪ (מחיר עלות)*.

### Initiative Validation Details

Source: Work WhatsApp group
Link to reputable source(s) promoting the initiative: Amit Segal (Telegram) https://t.me/s/amitsegal

### Initiative Category

children

### Initiative Form

https://docs.google.com/forms/d/e/1FAIpQLSdqaJqLlG5fJ0ZedfAtDR-M_YbtA0cET4XulxUVa0mIxmRO9g/viewform?fbzx=9104975861012066103

**Comment by 4tal** [comment]
Specific initiative, I don't think it's relevant. Reopen if you think yes
