### ISSUE TITLE
[NEW-INITIATIVE]: Team Me link for kidnapped videos

### ISSUE THREAD

**Issue by reututy** [4tals/LinksForIsrael#288]
### Initiative Name

Team Me

### Initiative Description

תוסף וידאו על החטופים למפתחי אתרים

### Initiative Details

חברת Team Me נרתמה לעזור להפיץ את הסיפור של החטופים בכל מקום בעולם. הוסיפו עוד היום את התוסף לאתר שלכם!

מה עשינו?

בנינו תוסף וידאו לאתרים עם כלל הסרטונים של משפחות החטופים כך שכל אתר בארץ או בעולם יוכלו להטמיע בקלות את התוסף ולעזור להעלות מודעות.

איך זה עובד?

1. נכנסים לאתר october7hostages.com
2. מעתיקים את הקוד שנמצא שם
3. מטמיעים את הקוד בכל אתר שתרצו (זה פחות מדקה עבודה)
4. מיד תראו את התוסף וידאו מצטרף לאתר שלכם 
5. עזרתם לנו ככה להגיע לעוד המון אנשים בעולם - תודה!

וככה נמשיך להעלות את המודעות גם בארץ אבל בעיקר בחול לסיפורים של החטופים.

לא פחות חשוב- בתוסף עצמו יש כפתור CTA שקורא לגולשים שלכם לתרום למטה החטופים.

### Initiative Validation Details

october7hostages.com

initiativeImage:https://static.wixstatic.com/media/af3a67_e3b72f829f3d42d68b868b1ee9172c11~mv2.jpeg/v1/fill/w_962,h_660,al_c,q_85,usm_0.66_1.00_0.01,enc_auto/af3a67_e3b72f829f3d42d68b868b1ee9172c11~mv2.jpeg

### Initiative Category

hasbara

**Comment by 4tal** [comment]
Done
