### ISSUE TITLE
[NEW-INITIATIVE-FORCE-PR]: בוט הברזל

### ISSUE THREAD

**Issue by ohadschn** [4tals/LinksForIsrael#29]
### Initiative Name
IronBot

### Initiative Description
להתחבר בקלות לכל סיוע אפשרי

### Initiative Details
בעזרת מערכת חיבורים חכמה, בוט הברזל יחבר אותכם במהירות לעמותות גופים ומתנדבים הרלוונטים לצורך שלכם, בכל רחבי הארץ.
ניתן לפנות לעזרה, התנדבות או מציאת תעסוקה למפונים.

בלחיצה על הכפתור תעברו לוואצאפ, תכתבו היי, תישאלו שאלות על מנת לברר פרטים ותקבלו את העזרה שאתם צריכים!

### Initiative Validation Details
https://www.ynet.co.il/digital/technews/article/bys217vwt

### Initiative Category
GeneralAssistance

### Initiative url
https://startach.org.il/%D7%91%D7%95%D7%98-%D7%94%D7%91%D7%A8%D7%96%D7%9C/

### Initiative Website
https://startach.org.il/%D7%91%D7%95%D7%98-%D7%94%D7%91%D7%A8%D7%96%D7%9C/

### Initiative WhatsApp
http://tiny.cc/ek3cvz

### Initiative donation
https://www.matara.pro/nedarimplus/online/?mosad=7008515

### Initiative Facebook
https://www.facebook.com/StartAchCom

### Initiative e-mail
mailto:startach@gmail.com

### Initiative Instagram
https://www.instagram.com/startachh

### Initiative LinkedIn
https://www.linkedin.com/company/startach

**Comment by 4tal** [comment]
#45

**Comment by ohadschn** [comment]
> #45
I don't see it added...
