### ISSUE TITLE
[NEW-INITIATIVE]: ביחד בשעת חירום

### ISSUE THREAD

**Issue by ohads-MSFT** [4tals/LinksForIsrael#296]
### Initiative Name

Together in Emergency

### Initiative Description

התארגנות וסיוע במצבי חירום

### Initiative Details

Looks like another aggregator, includes many initiatives:

[מתנדבים בעורף](https://together-ecosystem.com/emergency)
[סיוע באריזה](https://together-ecosystem.com/emergency/Emergency1/card-details/event/6538e8d833e7042f94dbc7f4)
סיוע באריזה

[תרומות ציוד](https://together-ecosystem.com/emergency/Emergency1/card-details/event/6538e85833e7042f94dbc7d8)
תרומות ציוד

[סיוע ביגוד חם](https://together-ecosystem.com/emergency/Emergency1/card-details/event/6538e7a433e7042f94dbc787)
סיוע ביגוד חם

 [אירגון אריזות מזון](https://together-ecosystem.com/emergency/Emergency1/card-details/event/6538e6c433e7042f94dbc73a)
אירגון אריזות מזון

[עזרה בחזית](https://together-ecosystem.com/emergency)
[אוכל ביתי לחיילים](https://together-ecosystem.com/emergency/Emergency2/card-details/event/6538eb1833e7042f94dbc93b)
אוכל ביתי לחיילים

[סיוע במוקד ל60+](https://together-ecosystem.com/emergency/Emergency2/card-details/event/6538ea8933e7042f94dbc930)
סיוע במוקד ל60+

[פריסה בשטח](https://together-ecosystem.com/emergency/Emergency2/card-details/event/6538e99733e7042f94dbc87f)
פריסה בשטח

[איסוף מזון וציוד](https://together-ecosystem.com/emergency/Emergency2/card-details/event/653898abda9342b030a05957)
איסוף מזון וציוד

[התנדבות / עזרה רפואית](https://together-ecosystem.com/emergency)
[עזרה ראשונה](https://together-ecosystem.com/emergency/Emergency3/card-details/event/6538ed4933e7042f94dbc9ce)
עזרה ראשונה

[הצטרפות למד״א](https://together-ecosystem.com/emergency/Emergency3/card-details/event/6538ecd633e7042f94dbc9b5)
הצטרפות למד״א

[אריזת חבילות](https://together-ecosystem.com/emergency/Emergency3/card-details/event/6538ec6c33e7042f94dbc992)
אריזת חבילות

[תרומות דם](https://together-ecosystem.com/emergency/Emergency3/card-details/event/6538ebee33e7042f94dbc96f)
תרומות דם

[מארזי מים](https://together-ecosystem.com/emergency/Emergency3/card-details/event/65389a2ada9342b030a059ea)
מארזי מים

[כיבוי והצלה](https://together-ecosystem.com/emergency)
[הצלה וסיוע](https://together-ecosystem.com/emergency/Emergency4/card-details/event/6538ee4f33e7042f94dbca4c)
הצלה וסיוע

[פרמדיקים לכוננות](https://together-ecosystem.com/emergency/Emergency4/card-details/event/6538ede933e7042f94dbca35)
[פרמדיקים](https://together-ecosystem.com/emergency/Emergency4/card-details/event/65389ed8da9342b030a05bef) לכוננות

פרמדיקים
פרמדיקים

[שמירה בישובים](https://together-ecosystem.com/emergency)
[מוקד טלפוני עירוני](https://together-ecosystem.com/emergency/Emergency5/card-details/event/6538ef9f33e7042f94dbcaab)
מוקד טלפוני עירוני

[הגנה על הישוב](https://together-ecosystem.com/emergency/Emergency5/card-details/event/6538ef2b33e7042f94dbca94)
הגנה על הישוב

[כיתת כוננות - נגה](https://together-ecosystem.com/emergency/Emergency5/card-details/event/6538eed633e7042f94dbca7b)
כיתת כוננות - נגה

[אירוח משפחות](https://together-ecosystem.com/emergency)
[אירוח משפחות](https://together-ecosystem.com/emergency/Emergency6/card-details/event/6538f22133e7042f94dbcb70)
אירוח משפחות

[פעילויות וכיף](https://together-ecosystem.com/emergency/Emergency6/card-details/event/6538f13133e7042f94dbcb12)
פעילויות וכיף

[הדלקת נרות](https://together-ecosystem.com/emergency/Emergency6/card-details/event/6538f0ac33e7042f94dbcaf0)
הדלקת נרות

[פעילויות לילדים](https://together-ecosystem.com/emergency/Emergency6/card-details/event/6538f04833e7042f94dbcad7)
פעילויות לילדים

[סיוע לבעלי חיים](https://together-ecosystem.com/emergency)
[התנדבות - ביה״ח](https://together-ecosystem.com/emergency/Emergency7/card-details/event/6538f32833e7042f94dbcbbf)
התנדבות - ביה״ח

[אימוץ חבר](https://together-ecosystem.com/emergency/Emergency7/card-details/event/6538f2b133e7042f94dbcba8)
אימוץ חבר

[הוצאת כלבים לטיול](https://together-ecosystem.com/emergency/Emergency7/card-details/event/6538a6e2da9342b030a05ef0)
הוצאת כלבים לטיול

### Initiative Validation Details

Source: Work WhatsApp group

### Initiative Category

InitiativesAggregation/Aggregation

### Initiative Website

https://together-ecosystem.com/emergency

**Comment by 4tal** [comment]
Done
