### ISSUE TITLE
[NEW-INITIATIVE]: השומר החדש

### ISSUE THREAD

**Issue by ohads-MSFT** [4tals/LinksForIsrael#297]
### Initiative Name

New Guard

### Initiative Description

חמ"ל החירום של ארגון השומר החדש - גיוס מתנדבים לאבטחת חוות, סיוע חקלאי 

### Initiative Details

ביטחון המזון של ישראל בסכנה!
עקב המצב, חקלאים ועובדיהם גויסו לשירות מילואים, חלקם נרצחו או נפצעו, עובדים זרים נטשו ומשקים חקלאיים נותרו לבדם, ללא ידיים עובדות ועם תוצרת חקלאית בשלה שחייבת להיקטף, חיות משק שדורשות טיפול ומשימות נוספות שאין מי שיעשה.

ארגון השומר החדש שמפעיל מתחילת המלחמה חמ"ל לגיוס אלפי מתנדבים שמסייעים לחקלאים, משקים וחוות בכל הארץ, יוצא במבצע חירום לאומי!

מתגייסים להצלת החקלאות והמזון בישראל

יחידים, קבוצות, ארגונים, ישיבות, מכינות, בתי ספר ותכניות חינוכיות
בואו לקחת חלק ולסייע בהתנדבות חקלאית ובמשימה הלאומית של הצלת החקלאות והמזון של ישראל.

### Initiative Validation Details

Source: well known organization way before the war

### Initiative Category

volunteering

### Initiative Website

https://www.hashomer.org.il/

**Comment by 4tal** [comment]
Done
