### ISSUE TITLE
[NEW-INITIATIVE]: פיטורי הברזל

### ISSUE THREAD

**Issue by ohadschn** [4tals/LinksForIsrael#301]
### Initiative Name

The Iron Fire - פיטורי הברזל

### Initiative Description

כלי עזר לדיווח למעסיקים בינלאומיים על עובדים המפיצים תוכן התומך בטרור החמאס

### Initiative Details

 ביחד ניצור השלכות אישיות לתומכי טרור ומפיצי שנאה
?כיצד להלחם בתומכי החמאס
 ארגונים רבים מכירים בחמאס כגוף טרור ולא היו רוצים להעסיק עובדים בתומכים בארגון טרור. בוא נסייע להם! אם נתקלתם בפוסט של תומך חמאס ברשת חברתית

 צלמו את הפוסט והעתיקו את הלינק לפוסט
 מצאו את פרופיל הלינקדאין של מפרסם הפוסט
 והזינו את הפרטים אל הטופס באתר פיטורי הברזל
 מערכת האוטומציה של האתר תמצא את כתובת המייל של המעסיק ותשלח להן אימייל מנוסח עם העדיות שאספתם

תרצו לקבל העתק של המיילים הנשלחים? הזינו את כתובת המייל שלכם בטופס ותקבלו העתק מוסתר

שימו לב, לאחר ההגשה התהליך דורש בין 10-15 דקות, אז יש להעזר בסבלנות

### Initiative Validation Details

Source: Passed in WhatsApp group
Link to reputable source(s) promoting the initiative: https://twitter.com/NaorNarkis/status/1717182734802526236
Looks like a legit account that was created over 8 years ago and has almost 11K subscribers

### Initiative Category

social-network, defence 

### Initiative Website

https://the-iron-fire.unicornplatform.page/

### Initiative X (Twitter)

https://twitter.com/unicornplatform

**Comment by 4tal** [comment]
Regenerated the record and took it straight from the logs.

{
      "name": "The Iron Fire - פיטורי הברזל",
      "displayName": "פיטורי הברזל - The Iron Fire",
      "description": "כלי עזר לדיווח למעסיקים בינלאומיים על עובדים המפיצים תוכן התומך בטרור החמאס",
      "initiativeValidationDetails": "נמסר בקבוצת WhatsApp. נראה כמו חשבון לגיטימי שנוצר לפני למעלה מ-8 שנים ויש לו כמעט 11 אלף מנויים",
      "website": "https://the-iron-fire.unicornplatform.page/",
      "twitter": "https://twitter.com/unicornplatform",
      "article": "https://twitter.com/NaorNarkis/status/1717182734802526236",
      "tags": [
        "רשת-חברתית",
        "הגנה",
        "פיטורים",
        "הסברה",
        "בינלאומי"
      ]
    }

Done
