### ISSUE TITLE
[NEW-INITIATIVE]: סאנדו התנדבות בחקלאות

### ISSUE THREAD

**Issue by ohadschn** [4tals/LinksForIsrael#302]
[NEW-INITIATIVE]: סאנדו התנדבות בחקלאות
### Initiative Name

SunDo Agriculture Volunteering

### Initiative Description

מקום אחד שמחבר במהירות בין חקלאים שצריכים עזרה ומתנדבים שיכולים להביא אותה

### Initiative Details

**הערה: אולי כדאי להוסיף תת קטגוריה של התנדבות בחקלאות**

סאנדו הינה פלטפורמה המחברת חקלאים ומתנדבים לסיוע חקלאי, משמעותי וחוויתי. בעזרת אפליקציית סאנדו, יכול כל אחד למצוא את הפעילות הנכונה, בזמן ובמקום המתאים לו.הורידו את סאנדו והתחברו גם אתם לקהילה החברתית חקלאית של ישראל!

### Initiative Validation Details

Source: Telegram Group
Link to reputable source(s) promoting the initiative: https://www.hashomer.org.il/featured_item/sundo/
השומר הצעיר עמותה ידועה ותיקה ואמינה

### Initiative Category

volunteering

### Initiative Website

https://www.hashomer.org.il/featured_item/sundo/

**Comment by 4tal** [comment]
{
   "name": "SunDo Agriculture Volunteering",
   "displayName": "סאנדו התנדבות בחקלאות",
   "description": "פלטפורמה המחברת חקלאים ומתנדבים לסיוע חקלאי, משמעותי וחוויתי. עם אפליקציית סאנדו, כל אחד יכול למצוא פעילות נכונה.",
   "url": "https://www.hashomer.org.il/featured_item/sundo/",
   "initiativeValidationDetails": "המקור: הקבוצה בטלגרם. הקישור למקור מאוד מוכר שמקדם את היוזמה: https://www.hashomer.org.il/featured_item/sundo/ השומר הצעיר - עמותה ידועה ומהימנה.",
   "tags": ["התנדבות","חקלאות","סאנדו","חקלאים","חוויתי","משמעותי"]
}
