### ISSUE TITLE
[NEW-INITIATIVE]: Nili Online

### ISSUE THREAD

**Issue by 4tal** [4tals/LinksForIsrael#304]
### Initiative Name

נילי אונליין

### Initiative Description

"ניל"י-אונליין" הוא פרויקט מיוחד שהוקם ע"י אזרחים שלא מוכנים לשכוח לכל מי שהביע אהדה, שמחה ושבח לאחר הטבח שבוצע ע"י חמאס-דעאש ב.7.10.23.

### Initiative Details

אמ;לק - פלטפורמה לדיווח של סטודנטים תומכי טרור 👇🏼

"ניל"י-אונליין" הוא פרויקט מיוחד שהוקם ע"י אזרחים שלא מוכנים לשכוח לכל מי שהביע אהדה, שמחה ושבח לאחר הטבח שבוצע ע"י חמאס-דעאש ב.7.10.23.

המטרה של "ניל"י-אונליין" (ע"ש היחידה שהשב"כ הקים אחרי הטבח) היא הקמת אתר אינטרנט שבו יופיעו תמונותיהם ושמותם כל תומכי ומשבחי הטבח בדרום.
מדגישים- כל מסית שיעלה לאתר המדובר, יופיע לצד תמונות והוכחות חותכות של הפוסט המסית והמביע אהדה ושבח לטרור הנאצי של חמאס-דעאש.

באתר יופיעו אנשים כמו: עו"ד (בדימוס) אסאלה אבו-כדר, השחקנית מאיסה עבד אלהאדי וכו'.

האתר יוקם על ידנו באופן וולונטרי לחלוטין ובימים אלו אנו עסוקים באיסוף החומרים.

המוטיבציה לכך נולדה מ2 סיבות:
1. לחברה הישראלית יש זיכרון-קצר.
2.ההבנה שהמשטרה והפרקליטות ירתיעו את המסיתים לטווח קצר,
אך בטווח הארוך כנראה שכל תומכי הטרור שצצו אחרי הטבח יחזרו למסלול חיים תקין.
לאחר יעבור זעם, הם ירצו לעבוד פה, הם ירצו ללמוד פה.

אנחנו פה כדי שזה לא יקרה.

המטרה שלנו זה להוקיע אותם מהחברה הישראלית, לנצח. כל מעסיק, גוף, אוניברסיטה, מכללה – שירצו, יוכלו לגשת לאתר וע"י חיפוש קצר של השם לדעת האם האדם שמולם הביע תמיכה בטרור ובטבח בדרום.

נתקלתם בפרסומים ברשת המביעים תמיכה, עידוד או שבח במעשים של חמאס-דאעש? אנא דווחו לנו באחד מהערוצים הבאים;
1.עמוד הפייסבוק - "ניל״י-אונליין" - https://www.facebook.com/profile.php?id=61552513511608

2.טופס ייעודי לדיווח אנונימי בקישור הנ"ל:
https://forms.gle/WYi2Vs55iead9zYj9

חפשו אותנו בטלגרם "אונליין-ניל"י" - https://t.me/onlinenili

הפיצו ושתפו בכל הכח. 🇮🇱

### Initiative Validation Details

Source: Are you the developer? If not, how did you hear about it? Link to reputable source(s) promoting the initiative: [e.g. https://www.israelhayom.co.il/tech/tech-news/iron-swords] Contact details for members of the initiative's team (so we can contact them directlyנתקלתם בפרסומים ברשת המביעים תמיכה, עידוד או שבח במעשים של חמאס-דאעש? אנא דווחו לנו באחד מהערוצים הבאים;
1.עמוד הפייסבוק - "ניל״י-אונליין" - https://www.facebook.com/profile.php?id=61552513511608
 for validation): [e.g. info@iron-widgets.com]

### Initiative Category

SocialNetworks

### Initiative Website

https://t.me/onlinenili

### Initiative Telegram

https://t.me/onlinenili

### Initiative Form

https://forms.gle/WYi2Vs55iead9zYj9

**Comment by ohadschn** [comment]
Looks like a dup of https://github.com/4tals/LinksForIsrael/issues/305
