### ISSUE TITLE
[NEW-INITIATIVE]: העוגן למשפחות המילואים

### ISSUE THREAD

**Issue by ohadschn** [4tals/LinksForIsrael#307]
[[NEW-INITIATIVE]: העוגן למשפחות המילואים#307](https://github.com/4tals/LinksForIsrael/issues/307)

### Initiative Name

The Anchor for Reserve Families

### Initiative Description

עזרה למשפחות משרתי מילואים, משרתי קבע והורים יחדניים מגני תקווה 

### Initiative Details

אנו מציעים סיוע במגוון תחומים: 
עם הילדים, עם הקניות לבית, הכנת אוכל תמיכה רגשית וכל מה שצריך. 

### Initiative Validation Details

Source: WhatsApp group
Link to reputable source(s) promoting the initiative: https://govextra.gov.il/muni/maaleedomim/home/
Contact details for members of the initiative's team (so we can contact them directly for validation): https://www.facebook.com/rachel.azaria/?locale=he_IL

### Initiative Category

Reserves

### Initiative Website

https://bit.ly/m/haogen4families

### Initiative Facebook

https://www.facebook.com/haogen4families?locale=he_IL

_No response_

### Initiative Form

https://forms.monday.com/forms/283d7bd8e98ba4fc2f2f1ab888c455a0?r=euc1

**Comment by 4tal** [comment]
Done
