### ISSUE TITLE
[NEW-INITIATIVE]: יד ביד למפונים

### ISSUE THREAD

**Issue by ohadschn** [4tals/LinksForIsrael#308]
[NEW-INITIATIVE]: יד ביד למפונים #308

### Initiative Name

Hand In Hand for evacuees

### Initiative Description

היד שמחברת בין בעלי מקצוע שנאלצו להתפנות מבתיהם, לתושבים שמחפשים בעל מקצוע

### Initiative Details

**הערה: אולי כדאי להוסיף קטגורית "מפונים" שבה תהיה תת-קטגוריה של אירוח משפחות ותת-קטגוריה של עזרה כללית כמו זאת**

חיזוק
האתר מסייע לתושבי הדרום והצפון, שנאלצו לעזוב את ביתם, להתפרנס במקצועם באזור מגוריהם הנוכחי
2
ערבות הדדית
האתר מקשר בין אנשים שמחפשים בעל מקצוע לבין מקצוענים שמעוניינים לספק שירותים
3
קהילה חזקה
חיבור אישי בין תושבי המדינה, לחיזוק הלכידות החברתית

### Initiative Validation Details

Source: Sent by a friend
Link to reputable source(s) promoting the initiative: https://www.ice.co.il/digital-140/news/article/985019

### Initiative Category

FamilyHosting

### Initiative Website

https://ironpro.zigit.co.il/

**Comment by 4tal** [comment]
{
    "name": "HandInHandForEvacuees#308",
    "displayName": "יד ביד למפונים",
    "description": "היד שמחברת בין בעלי מקצוע שנאלצו להתפנות מבתיהם, לתושבים שמחפשים בעל מקצוע",
    "initiativeValidationDetails": "מקור: נשלח על ידי חבר. קישור לאתר מהימן המקדם את היוזמה: https://www.ice.co.il/digital-140/news/article/985019",
    "url": "https://ironpro.zigit.co.il/",
    "tags": ["סושיאל", "בעל מקצוע", "מפונים", " קהילה", "משפחות"]
}

**Comment by 4tal** [comment]
Done
