### ISSUE TITLE
[NEW-INITIATIVE]: חמל אופנועים מוטוזון

### ISSUE THREAD

**Issue by ohadschn** [4tals/LinksForIsrael#309]
[NEW-INITIATIVE]: חמ"ל אופנועים מוטוזון

### Initiative Name

MotoZon

### Initiative Description

חמל אופנועים

### Initiative Details

קבוצה של 900 אופנוענים, מבצעים שינוע של דברים קטנים, כמובן בהקשר הנוכחי.

### Initiative Validation Details

Source: WhatsApp group
Link to reputable source(s) promoting the initiative: Google search suggests they are legit and established https://www.google.com/search?q=motozon&oq=motozon&gs_lcrp=EgZjaHJvbWUyBggAEEUYOTIHCAEQABiABDIJCAIQABgKGIAEMgcIAxAAGIAEMgcIBBAAGIAEMgcIBRAAGIAEMgcIBhAAGIAEMgcIBxAAGIAEMgcICBAAGIAE0gEIMzAxMWowajGoAgCwAgA&sourceid=chrome&ie=UTF-8#ip=1

### Initiative Category

Transportation

### Initiative Website

https://sh.hagai.co/bikeil/intake

### Initiative Facebook

https://www.facebook.com/groups/motozon/

### Initiative Instagram

https://www.instagram.com/motozonil/

**Comment by 4tal** [comment]
Done
