### ISSUE TITLE
[NEW-INITIATIVE]: קישורי מוזי להתדנבות וסיוע

### ISSUE THREAD

**Issue by ohadschn** [4tals/LinksForIsrael#311]
### Initiative Name
Muzi Links

### Initiative Description

אספנו קבוצות שונות לסיוע – מלחמת חרבות ברזל (רשימה מתעדכנת)

### Initiative Details

Another link aggregator / linktree

### Initiative Validation Details

Source: Ran into them in a google search, looks legit: https://www.facebook.com/groups/muzi.co.il/

### Initiative Category

InitiativesAggregation/Aggregation

### Initiative Website

https://muzi.co.il/event/%D7%91%D7%99%D7%97%D7%93-%D7%A0%D7%A0%D7%A6%D7%97/

**Comment by 4tal** [comment]
initiativeImage: 
https://muzi.co.il/wp-content/themes/muzi-theme/assets/images/icon_logo.png
