### ISSUE TITLE
[NEW-INITIATIVE]: מיזם הרחפנים הלאומי

### ISSUE THREAD

**Issue by ohadschn** [4tals/LinksForIsrael#313]
### Initiative Name

[[NEW-INITIATIVE]: מיזם הרחפנים הלאומי#313
National Drone Initiative

### Initiative Description

בהמשך לאירועי ה-7 באוקטובר, הצטרף מיזם הרחפנים הלאומי למאמץ החירום בניהול המרחב האווירי וביצוע פעילויות חוזי עבור גופים ציבוריים.

### Initiative Details

מיזם הרחפנים הלאומי המשותף לרשות החדשנות, משרד התחבורה, נתיבי איילון ורשות התעופה האזרחית פועל מזה שלוש שנים ובימים אלו משקיע את מירב המאמצים כדי להקצות את הידע והניסיון שצבר בעולם הטכנולוגי, התחבורתי הרגולטורי כדי לתמוך בהפעלת רחפנים לסיוע במאמץ הלאומי. המיזם הקים מרכז ניהול ובקרה אשר מאפשר הפעלה של כלי טיס בלתי מאוישים במרחב האווירי, 

השלב הראשון של מיזם הרחפנים הלאומי שהתקיים בין 2019 ל-2022 התמקד בהטסה של מטענים קטנים. השלב הנוכחי מטרתו להגדיל את משקלי הנשיאה והטווחים, כך שבעתיד תתאפשר הטסה של מטענים כבדים יותר ונוסעים. כמו כן, במסגרת ההדגמות נסללת “מערכת כבישים בשמיים” שתאפשר פעילות טיסות שוטפת בשמי הארץ כך שיוכלו לטוס במקביל מספר רחפנים וכלי טיס שונים למגוון שימושים, כולל בריאות, קמעונאות, ביטחון, בטיחות ועוד. מיזם הרחפנים עוסק גם בהסדרת המרחב האווירי ובניית תשתיות רגולטוריות להטסת כלים אוטונומיים לתועלת הציבור. בשלוש השנים האחרונות בוצעו במסגרת המיזם מעל מרחבים אורבניים ומרחבי ספר, למעלה מ-19,000 גיחות. בשנתיים הקרובות, החברות המשתתפות במיזם ימשיכו לבצע טיסות ברחבי הארץ למשך שבוע בכל חודש. הטיסות תבוצענה במרחב אווירי מנוהל, בפריסה ארצית למרחקים ארוכים של עד 150 קילומטרים, תוך נשיאת מטענים כבדים יותר, בכללם כלים שיאפשרו בעתיד גם הטסה של בני אדם. המיזם עובד בשיתוף פעולה עם גופים מסחריים וציבוריים נוספים – חיל אוויר, רשות שדות התעופה, רשויות מקומיות וגופים רלוונטיים נוספים.

במיזם שותפות החברות: 

אירוויז דרונז – Airwayz
היילנדר תעופה – High Lander
 קנדו דרונס – Cando Drones
רובוטיקאן – ROBOTICAN 
אף. טי. פתרונות אוויריים בע”מ 
Elsight- אלסייט
AGL- איגיאל
AIR TAXI ISRAEL (ATI)- מונית אווירית ישראל
DOWN WIND- דאון-וינד
Kronos group – קרונוס
ברוק – BROOK

### Initiative Validation Details

Source: WhatsApp group
 Link to reputable source(s) promoting the initiative: https://innovationisrael.org.il/civiliandronecenter/# 
האתר השרמיהרשמי של רשות החדשנות

### Initiative Category

volunteering

### Initiative Website

https://innovationisrael.org.il/civiliandronecenter/

**Comment by 4tal** [comment]
{
    "name": "מיזם הרחפנים הלאומי",
    "displayName": "מיזם הרחפנים הלאומי - National Drone Initiative",
    "shortDescription": "",
    "description": "מיזם הרחפנים הלאומי עוסק בהסדרת המרחב האווירי ובניית תשתיות רגולטוריות להטסת כלים אוטונומיים לתועלת הציבור.",
    "url": "https://innovationisrael.org.il/civiliandronecenter/",
    "initiativeValidationDetails": "המקור: קבוצת וואטסאפ. קישור למקור מהימן שמקדם את המיזם: [https://innovationisrael.org.il/civiliandronecenter/.](https://innovationisrael.org.il/civiliandronecenter/) האתר הרשמי של רשות החדשנות.",
    "tags": ["התנדבות","רחפנים","חידוש","הרחפנים הלאומי","מיזם","רחפן","טכנולוגיה"]
}

**Comment by 4tal** [comment]
Done
