### ISSUE TITLE
Automatic new initiative PR comment (GPT) - sanitize fields

### ISSUE THREAD

**Issue by ohadschn** [4tals/LinksForIsrael#314]
Failed run: https://github.com/4tals/LinksForIsrael/actions/runs/6656918174
I think it failed because there are quotes (`"`) in the title: https://github.com/4tals/LinksForIsrael/issues/309
> [NEW-INITIATIVE]: חמ"ל אופנועים מוטוזון #309

**Comment by 4tal** [comment]
@DanielShterenberg  Want to take it?
