### ISSUE TITLE
Overflow long categories to the next column

### ISSUE THREAD

**Issue by ohadschn** [4tals/LinksForIsrael#315]
In the screenshot below, there is a lot of wasted space that's reserved for other sub-categories even when they don't exist.
Perhaps we should treat all initiatives the same (With the same flow behavior), and just add a title separator for sub-categories (in other words, one big list that flows to the next column, with a title to indicate when a new sub-category starts).

![image](https://github.com/4tals/LinksForIsrael/assets/8555641/4bbabb9e-07d2-464a-a4e1-0612213b699f)

**Comment by Anatolysco** [comment]
Current version might solve this issue. Also we can use these cards for future versions
![Home v 4](https://github.com/4tals/LinksForIsrael/assets/12582720/99f9f374-0c49-4256-ac91-770991f00425)
Figma:
https://www.figma.com/file/BxHCYKopVxDdMmuIoOQ0AL/Look-and-Feel?type=design&node-id=237-28026&mode=design&t=uxHKVAXXqXtcUtpD-4

**Comment by 4tal** [comment]
Done

![Image](https://github.com/4tals/LinksForIsrael/assets/6404507/eaf82e9d-6fb4-4e31-9f8c-3888ed268276)
