### ISSUE TITLE
[NEW-INITIATIVE]: Medical Volunteers for Israel

### ISSUE THREAD

**Issue by ohadschn** [4tals/LinksForIsrael#325]
### Initiative Name

Medical Volunteers for Israel

### Initiative Description

The Israeli Ministry of Health is building a list of medical personnel from abroad to volunteer in Israel should the need arise.

### Initiative Details

In the event of further strains on the health system, as well as in preparation for future natural or man-made disasters, we invite friends of Israel to add their names to our growing community of medical personnel who stand with Israel. 

Sign up for the opportunity to receive CME credits in the future, train with Israeli teams, and connect with friends of Israel in your area.

Doctors, nurses, paramedics, and other medical personnel licensed abroad who wish to volunteer should join using the Ministry of Health’s online form, to ensure pre-clearance of medical licenses. 

We thank you in advance for signing up - and for standing with Israel.

### Initiative Validation Details

Source: official Ministry of health page

### Initiative Category

Medical

### Initiative Website

https://survey.gov.il/en/internationalvolunteers?utm_source=go.gov.il&utm_medium=referral

### Initiative WhatsApp

initiativeImage: https://survey.gov.il/sites/default/files/styles/medium/public/2023-10/%D7%A1%D7%9E%D7%9C%20%D7%94%D7%9E%D7%93%D7%99%D7%A0%D7%94-%20%D7%9B%D7%97%D7%95%D7%9C%20%D7%9B%D7%94%D7%94%20%D7%9E%D7%91%20copy%202.png?itok=7m2Yd5U0

**Comment by 4tal** [comment]
Done
