### ISSUE TITLE
[NEW-INITIATIVE]: https://oct7map.com/

### ISSUE THREAD

**Issue by 4tal** [4tals/LinksForIsrael#343]
### Initiative Name

Mapping the Massacres

### Initiative Description

The October 7th Geo-visualization Project strives to provide a comprehensive representation of the atrocities committed by Hamas on that day. This interactive map serves as a reflection and an educational tool, promoting awareness of the gravity of the horrors.

### Initiative Details

The October 7th Geo-visualization Project strives to provide a comprehensive representation of the atrocities committed by Hamas on that day. This interactive map serves as a reflection and an educational tool, promoting awareness of the gravity of the horrors.

### Initiative Validation Details

Source: Are you the developer? If not, how did you hear about it?
Link to reputable source(s) promoting the initiative: [e.g. https://www.israelhayom.co.il/tech/tech-news/iron-swords]
Contact details for members of the initiative's team (so we can contact them directly for validation): [e.g. info@iron-widgets.com]

### Initiative Category

hasbara

### Initiative main URL

https://oct7map.com/

### Initiative Website

https://oct7map.com/

### Initiative Tags

מיפוי, ויזואליזציה

**Comment by ohadschn** [comment]
> If I missed it, many more will do

Fair point, should we make it mandatory?

**Comment by 4tal** [comment]
Let's take it to - https://github.com/orgs/4tals/projects/1/views/2?pane=issue&itemId=43226880?

**Comment by 4tal** [comment]
Done
