### ISSUE TITLE
[NEW-INITIATIVE]: צו גיוס

### ISSUE THREAD

**Issue by reututy** [4tals/LinksForIsrael#348]
### Initiative Name

ZGIL

### Initiative Description

עזרה נפשית

### Initiative Details

פוחדים? דואגים? 
מתקשים לישון? 
מוצפים במחשבות?
הכנסו בכל שעה לכאן - http://zgil.org.il
ותוך דקה איש מקצוע יחזור אליכם
יקשיב, יסייע, ירגיע.
אל תהססו...  בדיוק בשביל זה הוקם
"צו גיוס מאמנים ומטפלים – ישראל" http://zgil.org.il
24 שעות ביממה, אנחנו קשובים לכם!

### Initiative Validation Details

Reputable source: https://13tv.co.il/item/stronger-together/n13ik-903754667/

### Initiative Category

MentalSupport

**Comment by ohadschn** [comment]
@reututy we need to be careful about our validation - I've edited the issue to include a reputable source, in this case channel 13 (the website of the initiative you put there before typically doesn't count, unless it's placed under a trusted domain like a government `org.il` site)
