### ISSUE TITLE
[NEW-INITIATIVE]: עסקים בזמן מלחמה

### ISSUE THREAD

**Issue by reututy** [4tals/LinksForIsrael#349]
### Initiative Name

ALL CLUB

### Initiative Description

הטבות לעסקים בתקופת המלחמה

### Initiative Details

אנו קהילת ALL CLUB  הקהילה הראשונה והגדולה ביותר בישראל המונה מעל 200,000 חברים!
מזמינים אתכם להצטרף ולהנות מכלל השירותים שלנו – ללא עלות וללא התחייבות לתקופה של חודש!

### Initiative Validation Details

Reputable source: https://www.facebook.com/RaananaBusinessCenter/posts/pfbid0gpAgJa4dGnrgQWWGchgtcmDEfgFmqatRFntnBCp9MUiWSBuPGn4XpejELEZfeJdMl?locale=ms_MY

### Initiative Category

Economy/Main

### Initiative main URL

https://allclub.minisite.ms/71

**Comment by ohadschn** [comment]
@reututy same as the other ticket, I've added a reputable link

**Comment by ohadschn** [comment]
@4tal what do you think about a `Business` category?
