### ISSUE TITLE
Add the "Block The Hate" Bot

### ISSUE THREAD

**Issue by reututy** [4tals/LinksForIsrael#350]
### Initiative Name

Block The Hate

### Initiative Description

בוט שמוצא תוכן אלים, שקרי ואנטישמי לשם דיווח

### Initiative Details

חברים יקרים!

בשבוע האחרון הקמנו פרויקט מדהים שמטרתו להילחם בשנאה כלפי ישראל ברשתות.
הפלטפורמות השונות הפכו בימים אלו לזירת מלחמה נוספת אשר מכילה כמות אדירה של תכנים אלימים, שקריים ואנטישמיים. פוסטים מלאי שנאה כלפי ישראל מופצים לעולם ואנו חייבים להילחם בהם בכל הכח על מנת להסירם באופן מיידי.
פיתחנו בוט שסורק אוטומטית מאגרי מידע גדולים ברשת ועוזר ליוזרים להנגיש את תהליך מציאת הפוסטים העויינים, הדיווח עליהם וכפועל יוצא - חסימתם.

הבוט כבר זמין ונגיש לכולם דרך הטלגרם בלחיצת כפתור על הלינק הבא:
https://t.me/BlockTheHateIL_Bot

בקליק אחד נכנסים לבוט --> בוחרים את הפלטפורמות שבהן תרצו לדווח --> מתחילים לקבל פוסטים שעברו סינון ונמצאו עויינים --> נכנסים לפוסט ומדווחים!
אנחנו צריכים אתכם איתנו!
התגייסו עכשיו והצטרפו אלינו למלחמה בשנאה על ידי שימוש יום-יומי פשוט של כמה דקות בבוט שבנינו.
יחד ננצח.

https://www.blockthehateil.com/

### Initiative Validation Details

Source: Are you the developer? If not, how did you hear about it?
Link to reputable source(s) promoting the initiative: [e.g. https://www.israelhayom.co.il/tech/tech-news/iron-swords]
Contact details for members of the initiative's team (so we can contact them directly for validation): [e.g. info@iron-widgets.com]

### Initiative Category

hasbara

**Comment by ohadschn** [comment]
@reututy as you suspected, we already have this on our site. 2 Easy ways to check next time:
1. Site search (see below)
2. Github search: https://github.com/search?q=repo%3A4tals%2FLinksForIsrael%20blockthehateil&type=code

![image](https://github.com/4tals/LinksForIsrael/assets/8555641/fa8a712e-585a-43d4-9f6a-a5bdf62060a2)
