### ISSUE TITLE
Add NILI online site

### ISSUE THREAD

**Issue by reututy** [4tals/LinksForIsrael#351]
### Initiative Name

ניל"י-אונליין

### Initiative Description

פלטפורמה לדיווח של סטודנטים תומכי טרור 

### Initiative Details

"ניל"י-אונליין" הוא פרויקט מיוחד שהוקם ע"י אזרחים שלא מוכנים לשכוח לכל מי שהביע אהדה, שמחה ושבח לאחר הטבח שבוצע ע"י חמאס-דעאש ב.7.10.23.

המטרה של "ניל"י-אונליין" (ע"ש היחידה שהשב"כ הקים אחרי הטבח) היא הקמת אתר אינטרנט שבו יופיעו תמונותיהם ושמותם כל תומכי ומשבחי הטבח בדרום.
מדגישים- כל מסית שיעלה לאתר המדובר, יופיע לצד תמונות והוכחות חותכות של הפוסט המסית והמביע אהדה ושבח לטרור הנאצי של חמאס-דעאש.

באתר יופיעו אנשים כמו: עו"ד (בדימוס) אסאלה אבו-כדר, השחקנית מאיסה עבד אלהאדי וכו'.

האתר יוקם על ידנו באופן וולונטרי לחלוטין ובימים אלו אנו עסוקים באיסוף החומרים.

המוטיבציה לכך נולדה מ2 סיבות:
1. לחברה הישראלית יש זיכרון-קצר.
2.ההבנה שהמשטרה והפרקליטות ירתיעו את המסיתים לטווח קצר,
אך בטווח הארוך כנראה שכל תומכי הטרור שצצו אחרי הטבח יחזרו למסלול חיים תקין.
לאחר יעבור זעם, הם ירצו לעבוד פה, הם ירצו ללמוד פה.

אנחנו פה כדי שזה לא יקרה.

המטרה שלנו זה להוקיע אותם מהחברה הישראלית, לנצח. כל מעסיק, גוף, אוניברסיטה, מכללה – שירצו, יוכלו לגשת לאתר וע"י חיפוש קצר של השם לדעת האם האדם שמולם הביע תמיכה בטרור ובטבח בדרום.

נתקלתם בפרסומים ברשת המביעים תמיכה, עידוד או שבח במעשים של חמאס-דאעש? אנא דווחו לנו באחד מהערוצים הבאים;
1.עמוד הפייסבוק - "ניל״י-אונליין" - https://www.facebook.com/profile.php?id=61552513511608

2.טופס ייעודי לדיווח אנונימי בקישור הנ"ל:
https://forms.gle/WYi2Vs55iead9zYj9

חפשו אותנו בטלגרם "אונליין-ניל"י" - https://t.me/onlinenili

### Initiative Validation Details

https://forms.gle/WYi2Vs55iead9zYj9

### Initiative Category

hasbara

### Initiative Telegram

https://t.me/onlinenili

### Initiative Form

https://forms.gle/WYi2Vs55iead9zYj9

### Initiative Facebook

https://www.facebook.com/profile.php?id=61552513511608

**Comment by ohadschn** [comment]
We already have this, for future reference 2 ways to check:
1. Site search (screenshot below)
2. Github search: https://github.com/search?q=repo%3A4tals%2FLinksForIsrael%20nili&type=code

![image](https://github.com/4tals/LinksForIsrael/assets/8555641/faa7b026-601e-4f91-a2c9-cd867b3e5102)
