### ISSUE TITLE
[NEW-INITIATIVE]: Add Subtitles for videos form

### ISSUE THREAD

**Issue by reututy** [4tals/LinksForIsrael#352]
### Initiative Name
Autocap

### Initiative Description
אפליקציית מובייל להוספת כתוביות לסרטונים בכל שפה
### Initiative Details
אפליקציה בתשלום אך מאפשרת שימוש חינם לטובת סרטוני הסברה לטובת ישראל,
כל מי שמעוניין שימלא את הטופס ויקבל מייל תגובה עם פרטי הורדה ושימוש חינמי.

האפליקציה מאפשרת לתמלל סרטונים ובסוף תהליך התמלול גם לתרגם בעזרת גוגל טרנסלייט

סרטון הסבר להתחברות לאפליקציה ללא תשלום עם כתובת המייל שנרשמת איתה:
https://youtube.com/shorts/4z_teM1A-ME

אנדרויד:
https://play.google.com/store/apps/details?id=com.laika.kinetictypovid&hl=en&gl=US&pli=1
(לא עובד טוב על שיאומי)

אפל:
https://apps.apple.com/us/app/autocap-video-captions/id1466743701

### Initiative Validation Details
Over 500K downloads in the android app store alone (Probably more in the Apple store): https://play.google.com/store/apps/details?id=com.laika.kinetictypovid&hl=en&gl=US&pli=1

### Initiative Category
StrategicCommunication/Tools

### Initiative main URL
 https://forms.gle/NSQS9dowb5VPuiFA7

### Initiative Website
http://autocap.app/

### Initiative Form
 https://forms.gle/NSQS9dowb5VPuiFA7

**Comment by ohadschn** [comment]
We already have this, for future reference 2 ways to check:
1. Site search (screenshot below)
2. Github search: https://github.com/search?q=repo%3A4tals%2FLinksForIsrael%20nili&type=code

![image](https://github.com/4tals/LinksForIsrael/assets/8555641/faa7b026-601e-4f91-a2c9-cd867b3e5102)

**Comment by ohadschn** [comment]
@reututy could you please provide validation details for this form?

**Comment by 4tal** [comment]
We need more information about the initiative, if we want to add it.

**Comment by ohadschn** [comment]
> We need more information about the initiative, if we want to add it.

I filled out the form, will update the description with the email I got
