### ISSUE TITLE
[NEW-INITIATIVE]: 

### ISSUE THREAD

**Issue by AdirD** [4tals/LinksForIsrael#357]
### Initiative Name

voicesOfIsrael

### Initiative Description

גוף תומך בפעילויות פרו-ישראלית מסביב לעולם

### Initiative Details

בעקבות מלחמת ׳חרבות הברזל׳, אנו מזמינים ארגונים, פרויקטים וגופים (עמותות, חברות, עוסקים מורשים) להגיש הצעות למיזמים לחיזוק הנרטיב של ישראל בזירה הבין לאומית בהקשר למאמץ ההסברתי מלחמתי.  פרויקטים שיבחרו יזכו למימון משלים – Match funding על בסיס תצהיר חתום על יכולות המימון, בשיעור של עד 50% מעלות התוכנית. ניתן למצוא את הפרטים המלאים באתר שלנו - https://voicesofisrael.org/
זמינים לשאלות בפרטי ובמייל. 
 info@voicesofisrael.org

### Initiative Validation Details

Source: Eden Eini 
נשלח בקבוצת וואטסאפ ״קבינט הסברה | אדמינים בלבד״

### Initiative Category

StrategicCommunication

### Initiative main URL

https://voicesofisrael.org/

### Initiative Website

https://voicesofisrael.org/

**Comment by 4tal** [comment]
<img width="1677" alt="image" src="https://github.com/4tals/LinksForIsrael/assets/6404507/6d64c95a-8a7a-40dd-b4ba-1b12e2498715">
