### ISSUE TITLE
Categories should be functional (focused on what the customer wants to do)

### ISSUE THREAD

**Issue by ohadschn** [4tals/LinksForIsrael#36]
For example, the category "technical initiatives" is not helpful, because such an initiative could be anything... When a customer enters the site, they have something in mind - they want to contribute money, they want information, they want to ask for equipment, etc. 

I think the categories should be something like:
1. _Donations_
2. _Information_
3. _Hosting families_
4. _Equipment / Food_
6. _Transportation_
7. _Professionals_  (e.g. software developers)
8. _Services_ (e.g. babysitting)
(And probably some more I can't think about at this hour)

It's important that for each applicable category, we clarify very clearly whether the link is for **providing/volunteering** or **receiving/asking for help**.

For inspiration, look at the categories here: https://linktr.ee/cherevotbarzel

**Comment by ohadschn** [comment]
@4tal I would call this complete except for "existing technical initiatives", whose links should be dispersed to the other existing (functional) categories

**Comment by 4tal** [comment]
Proposed to content Team.
