### ISSUE TITLE
[NEW-INITIATIVE] : לקט ישראל

### ISSUE THREAD

**Issue by itziktdk** [4tals/LinksForIsrael#361]
### Initiative Name

Leket Israel - Farmers Volonteers

### Initiative Description

התנדבות למשקים בדרום בעקבות המלחמה 

### Initiative Details

חקלאים רבים גוייסו למלחמה, ועובדים זרים עזבו את השדות. משקים חקלאיים נותרו ללא ידיים עובדות ועם תוצרת חקלאית שצריך לקטוף.

ארגון לקט ישראל מסייע לחקלאים בגיוס מתנדבים וקורא לכם לסייע לחקלאות הישראלית בעת משבר.

### Initiative Validation Details

Well established organization: https://en.wikipedia.org/wiki/Leket_Israel

### Initiative Category

Agriculture/Main

### Initiative main URL

https://www.leket.org/volunteering-for-farmers/

### Initiative WhatsApp

https://chat.whatsapp.com/CGrct4DA8i4B1LsvLZFsrk

**Comment by ohadschn** [comment]
Oh I see you merged it, sorry
