### ISSUE TITLE
Last item is in each sub-category is clipped without possibility to scroll

### ISSUE THREAD

**Issue by MoaidHathot** [4tals/LinksForIsrael#386]
# **EDIT:**  renamed title, see last comment below

**Describe the bug**
There is no way to scroll horizontally when the results of a category exceed the horizontal space (see picture below). 

**To Reproduce**
Steps to reproduce the behavior: Click on a category with a lot of results, [`Volunteering`](https://www.[linksforisrael.com](https://www.linksforisrael.com/Volunteering)/Volunteering) for example. 

**Expected behavior**
We should be able to scroll through the results or at least wrap them into new lines.

**Screenshots**
![image](https://github.com/4tals/LinksForIsrael/assets/8770486/804c98bc-5074-419a-b1fd-9cb78b3ad03d)

**Desktop (please complete the following information):**
- OS: Windows 11 - 23H2 (OS Build 22631.2506)
- Browser FireFox & Edge
- Version latest (both)

**Comment by ohadschn** [comment]
@MoaidHathot Does this still happen? I can't repro on either browser, perhaps you have some plugin that interferes?
![image](https://github.com/4tals/LinksForIsrael/assets/8555641/a0a8d62e-c22f-460a-bb63-85f6f569bd6f)

![image](https://github.com/4tals/LinksForIsrael/assets/8555641/5d0566b2-bed2-4b8b-9b39-2541495062ab)

In both browsers I get the horizontal scrolling bar...

**Comment by ohadschn** [comment]
Oh, I think I understand the case... when the **last** entry is clipped, you will get no scroller:
![image](https://github.com/4tals/LinksForIsrael/assets/8555641/f27aec3d-3d88-4b77-bcc6-b8401a2200f3)

So technically you can still click on all the links, but for sure I can see users thinking there are more they can't reach, as Moaid theorized above (not to mention the aesthetic issue)
