### ISSUE TITLE
[NEW-INITIATIVE]: ערוץ TOV - הסברה יהודית בזירה הבינלאומית

### ISSUE THREAD

**Issue by ohadschn** [4tals/LinksForIsrael#387]
### Initiative Name

TOV Strategic Communications

### Initiative Description

חזית יהודית בהסברה בינלאומית

### InitiativeImage
https://tovnews.co.il/wp-content/uploads/2023/10/Logo_Jewish_News_2023_new-1536x864.png

### Initiative Details

מה היה קורה בהסברה הבינלאומית אם כל העולם היה יכול לצפות בתכנים של ערוץ TOV בזמן אמת באנגלית?
מאות אלפי צופים מגיעים לתוכן של ערוץ TOV מדי שבוע קהל נאמן שמגיע לצפות, לעקוב להתעדכן ללמוד ולהחכים ולשמוע קול יהודי ישראלי צלול וחד. עכשיו הגיע הזמן לתת לתוכן הזה לפרוץ את גבולות הארץ ולהגיע לתפוצות ולשמש את ישראל כתוכן הסברה עמוק ומנומק.

דיבור יהודי אינטלקטואלי עמוק שלא חושש להגיד את האמת, להסביר ולפרשן אותה עם מיטב המומחים, יכול לגרום לשינוי אמיתי בתודעת הקהל העולמית שמוצפת בתוכן שיקרי ושטחי.

המטרה שלנו היא להפיץ בע"ה את התכנים שלנו בזמן אמת, מתורגמים ומדובבים לאנגלית ולשפות המרכזיות, ולחזק את הקול שלנו בקהילה הבינלאומית שתומכת בישראל בפרט ובעם היהודי בכלל.

רק דיבור יהודי צלול וברור יכול להביא את השינוי.

### Initiative Validation Details

Official website of TOV news (well known channel since long before the war)

### Initiative Category

StrategicCommunication/Funding

### Initiative main URL

https://tovnews.co.il/elementor-129903

### Initiative Website

https://tovnews.co.il/elementor-129903

**Comment by 4tal** [comment]
@ohadschn After adding it, I'm not sure it was in the right place, and I'm not sure. where it should go.

**Comment by ohadschn** [comment]
> https://tovnews.co.il/

@4tal Well they have "hasbara" in the name, so It has to be under `StrategicCommunication` right?
Which sub category, don't think it overly matters, they were asking for donations so I put funding but if you prefer one of the other ones that works for me
