### ISSUE TITLE
Feature Request: Enhanced Contributor Assistance Page and Link Item Status Indicators

### ISSUE THREAD

**Issue by 4tal** [4tals/LinksForIsrael#395]
Description
To facilitate better engagement and productivity among our open-source contributors, we propose the addition of a dedicated page for internal assistance within our web application. This page would serve as a centralized hub of resources and guidance, aimed at making the contribution process as seamless as possible. Additionally, we need a feature that clearly indicates which items in the initiatives index require more information or need corrections.

1. Contributor Assistance Page
A new page within the web application that includes:

Structured Navigation: for different types of tasks (documentation, coding, design, etc.).
Resource Links: Direct links to contribution guidelines, coding standards, setup instructions, and other relevant documentation.

FAQ Section: A compilation of frequently asked questions to help new contributors get up to speed.
Contact Info: Information on how to reach out for help, whether it's through a dedicated Slack channel, email, or GitHub discussions.

2. Link Item Status Indicators
An enhancement to the initiatives index to include:

Status Tags: Visual indicators (such as color-coded tags or icons) to show the status of a link item, e.g., 'Complete', 'Needs Info', 'Needs Correction'.
Hover-over Details: On hover, details should appear explaining what additional information is required or what needs to be corrected for that specific link item.
Filtering Capability: The ability to filter link items based on their status, so contributors can easily find where assistance is needed.
Justification
These enhancements are expected to:

Increase Efficiency: By reducing the time contributors spend searching for how to contribute effectively.
Improve Accuracy: By making it clear where contributions are needed most and what the specific requirements are.
Encourage Participation: By providing a friendly and supportive environment for both new and experienced contributors.
Resources and Links

**Comment by ohadschn** [comment]
1. We already have a page for this purpose, we can broaden it with your suggestions: https://github.com/4tals/LinksForIsrael/blob/main/docs/contribute.md
2. Where would those tags reside? It might not be wise to overload the customer (website) experience with info only relevant for contributors...

**Comment by 4tal** [comment]
Imo visual interaction is clearer and more welcoming. But I guess better guidance on contributing will do
