### ISSUE TITLE
Introduce UI component library (Fluent / Chakra)

### ISSUE THREAD

**Issue by 4tal** [4tals/LinksForIsrael#412]

**Comment by ohadschn** [comment]
@4tal renamed title to allow other UI frameworks to be chosen. 

I gather @omer-friedman is more familiar with FluentUI, that alone is a good argument for it (of course if all the other devs know Chakra that might change)

**Comment by 4tal** [comment]
![Image](https://github.com/4tals/LinksForIsrael/assets/6404507/cf22e450-64eb-4fad-9118-2e4f866c0ab0)
![Image](https://github.com/4tals/LinksForIsrael/assets/6404507/e3b393ee-85f3-4467-a82e-4da7d865018f)



It gives me a simplicity vibe in favor of Chakra:
![Image](https://github.com/4tals/LinksForIsrael/assets/6404507/96b010dd-cfa1-4e8a-ba52-d03c6a7c2f5d)
![Image](https://github.com/4tals/LinksForIsrael/assets/6404507/31c4cb25-3978-4b5d-a673-a985add18cae)

**Comment by 4tal** [comment]
@omer-friedman checkout the general info attached. Will be great to get your insights about this area.

**Comment by ohadschn** [comment]
@4tal you are missing some key data points

1. MS backing means a lot. Among other things, it means dogfooding - for example the Azure Portal uses it, so Microsoft is highly invested in its quality (recall cloud is its single most important business, by far).
2. Almost twice as mature (7 vs 4 years) and almost double the amount of commits
3. The **ratio** of open to closed issues is significantly better (also true for PRs, of which there are ~5.5X more)
4. Checking the pulse of the last month, fluent is much more active (I see a similar picture looking at the historical code frequency data as well)
5. As for popularity, meh. Once you cross some threshold, I think beyond that is a lot of personal taste. I doubt you'll read too much into this list, for example: https://madnight.github.io/githut/#/pull_requests/2023/3 (at least, I really hope you don't think Python is the best language ever)...

![image](https://github.com/4tals/LinksForIsrael/assets/8555641/513ef9a4-fa36-4c9d-869e-4cff3a69aa2d)

![image](https://github.com/4tals/LinksForIsrael/assets/8555641/bb1053cd-6000-4057-95fb-dd296ebefece)

![image](https://github.com/4tals/LinksForIsrael/assets/8555641/8d247654-5fa4-4f77-be5f-2b0774481403)

![image](https://github.com/4tals/LinksForIsrael/assets/8555641/f43585e0-7656-4577-888b-202f2f4d8de3)

![image](https://github.com/4tals/LinksForIsrael/assets/8555641/6b51a055-69ec-43ab-aec6-148f87dcf598)

![image](https://github.com/4tals/LinksForIsrael/assets/8555641/4dceff46-0ed6-41d7-a614-1c86d4d454e9)

![image](https://github.com/4tals/LinksForIsrael/assets/8555641/a926205f-aec2-408d-bbed-052ab8ab2ae7)

**Comment by 4tal** [comment]
Let's not dragged this into Philosophical debate, especially not face to face with something to drink.

I vote for Chakra is that it's considered more beginner friendly so easier to start participating using chakra even with no Design knowledge + I'm familiar with it (Solid long term development resource :))

**Comment by omer-friedman** [comment]
I agree with Ohad here, but I don't think its an extremely important desicion.
Chakra looks fine to me.
