### ISSUE TITLE
Class usage sometimes lead to coding overheads and be less readable and clear

### ISSUE THREAD

**Issue by 4tal** [4tals/LinksForIsrael#414]
Simplicity: For a straightforward task like sending a synchronous request and processing the response, procedural scripting can be more straightforward and easier to follow.

Single-use: If the script is intended for a one-off use or only performs a single function, the overhead of creating a class may be unnecessary.

Few Functions: If your script consists of only a few functions, and they are relatively independent, encapsulating them in a class may add unnecessary complexity.

No Object-Oriented Benefits: If your script doesn't benefit from object-oriented programming principles like inheritance, encapsulation, or polymorphism, using a class could be superfluous.

Ease of Understanding: Functions can be easier for others to understand when reading your script, especially for those who are not familiar with object-oriented programming.

Minimal Scope: If your script has a minimal scope and doesn't interact with other parts of a system where objects might be advantageous, sticking to functions is adequate.

**Comment by ohadschn** [comment]
@4tal what is this about? do you have examples?

**Comment by 4tal** [comment]
Avoid class based implementation for simplicoty

**Comment by ohadschn** [comment]
> Avoid class based implementation for simplicoty

do you have an example in mind?

**Comment by ohadschn** [comment]
@4tal my point is, if you don't have specific calls to action, this should be a discussion or guideline in some contribution markdown - not an issue that would remain open forever (at some point we'd want to reach zero issues too, not just 0 PRs...)

**Comment by 4tal** [comment]
Agree

**Comment by ohadschn** [comment]
> Agree

Could you convert it to a discussion please and close this, then?

**Comment by ohadschn** [comment]
@4tal closing for now, please re-open if you have anything concrete you with to implement, and/or start a discussion
