### ISSUE TITLE
How to solve Vercel member approval requirement for deployment

### ISSUE THREAD

**Issue by 4tal** [4tals/LinksForIsrael#425]
If not a member approve the code, it will not be deployed

**Comment by ohadschn** [comment]
> If not a member approve the code, it will not be deployed

I imagine this must be a definition of the account and/or the bot?
Anyway, pretty sure it will be resolved when we do this: https://github.com/4tals/LinksForIsrael/issues/294

**Comment by 4tal** [comment]
Verify it's not relevant for Public Github Repos.
