### ISSUE TITLE
Align left issues written in English

### ISSUE THREAD

**Issue by DanielShterenberg** [4tals/LinksForIsrael#481]
The text of an issue that is being described in English, should be aligned to the left 
![image](https://github.com/4tals/LinksForIsrael/assets/5736597/b7148694-5e11-4a61-a2f4-ffad0b81d8c6)

**Comment by omer-friedman** [comment]
the question is how to determine the language. 
 for example, this one has both english and hebrew in it: 
![image](https://github.com/4tals/LinksForIsrael/assets/34510256/90086660-0ece-4329-811a-a68422a9d34b)
as I see it we have two options.
1. enough to find one hebrew letter in the title or the description to determine RTL
2. add some property to the json that says if its RTL or LTR (or add the language)
wdyt?

**Comment by ohadschn** [comment]
> the question is how to determine the language. for example, this one has both english and hebrew in it: ![image](https://user-images.githubusercontent.com/34510256/282268409-90086660-0ece-4329-811a-a68422a9d34b.png) as I see it we have two options.
> 
> 1. enough to find one hebrew letter in the title or the description to determine RTL
> 2. add some property to the json that says if its RTL or LTR (or add the language)
>    wdyt?

I think option 1 is good enough (at least to start with)
