### ISSUE TITLE
New initiative logo / image should be downloaded, checked in the repo, and referenced by the auto PR (instead of referenced directly)

### ISSUE THREAD

**Issue by ohadschn** [4tals/LinksForIsrael#492]
Currently we just take the submitted URL, but that could easily change and break us
In the future, this could be something more sophisticated like Cloudinary upload

**Comment by ohadschn** [comment]
> Already have an account there with images for this project, if you're starting to work on it, ping me and I'll provide the relevant token / other info

There = cloudinary?

**Comment by 4tal** [comment]
yes
