### ISSUE TITLE
Iron Voice

### ISSUE THREAD

**Issue by DanielShterenberg** [4tals/LinksForIsrael#507]
### Initiative Name
Iron Voice

### Category
hasbara - הסברה

### Category
hasbara - הסברה

### Main Link
https://chat.openai.com/g/g-OFt3XQR3l-iron-voice

### Description
צט שניתן לשוחח איתו על עניינים שקשורים למלחמה, לקבל מידע, לינקים, וכמובן לנהל שיחה

### WhatsApp Link
N/A

### Remarks for Admins
N/A

### Telegram Link
N/A

### Drive Link
N/A

### Form Link
N/A

### Doc Link
N/A

### Discord Link
N/A

### Instagram Link
N/A

### TikTok Link
N/A

### Twitter/X Link
N/A

### Facebook Link
N/A

**Comment by 4tal** [comment]
It will lead to a mess if we'll stack them in LinksForIsrael
