### ISSUE TITLE
[NEW-INITIATIVE]: All for Israel

### ISSUE THREAD

**Issue by DanielShterenberg** [4tals/LinksForIsrael#520]
### Initiative Name
All for Israel

### Initiative Description
איסוף תרומות לרכישת מזון, ציוד וביגוד עבור החיילים בשטח והמפונים.

### Initiative Category
donations - תרומות

### Initiative main URL
https://all4israel.com

### Initiative WhatsApp
https://chat.whatsapp.com/LMxQxuWTozf3ry4EaB5zhe

### Initiative X (Twitter)
@4israelproject

**Comment by ohadschn** [comment]
Closing per comment in the other issue
