### ISSUE TITLE
[NEW-INITIATIVE]: חמ"ל משגב

### ISSUE THREAD

**Issue by DanielShterenberg** [4tals/LinksForIsrael#524]
### Initiative Name
חמ"ל משגב

### Initiative Description
חמ"ל משגב, הינה יוזמה קהילתית הפועלת בלב הגליל, שמטרתה לתמוך בחיילי צה"ל בצפון הארץ במזון וציוד. החמ"ל מספק מעל 1500 מנות לחיילים מדי יום. לחמ"ל שני מרכזים לוגיסטיים בשכניה ויובלים, המשמשות כנקודות לחלוקת ציוד ומזון חם. היוזמה כוללת למעלה מ-500 מתנדבים שעוסקים בבישול, נהיגה, ורכישות, כאשר 100% מהתקציב מיועד לחיילי הצפון.

### Initiative Category
EquipmentNFood - ציוד ומזון

### Initiative main URL
https://gofund.me/86bd07fc

**Comment by ohadschn** [comment]
Please see my comment on the associated PR
