### ISSUE TITLE
[NEW-INITIATIVE]: הכל למען ישראל

### ISSUE THREAD

**Issue by DanielShterenberg** [4tals/LinksForIsrael#530]
### Initiative Name
הכל למען ישראל

### Initiative Description
גיוס תרומות מכל העולם למען החיילים והמפונים.

### Initiative Category
donations - תרומות

### Initiative main URL
https://all4israel.com

### Initiative WhatsApp
https://chat.whatsapp.com/LMxQxuWTozf3ry4EaB5zhe

### Initiative X (Twitter)
@4israelproject

**Comment by ohadschn** [comment]
Closing per explanation in previous issues on the same initiative
