### ISSUE TITLE
Unify categories: Supplies & Transportation (also possibly remove Soldiers/Reserves category)

### ISSUE THREAD

**Issue by ohadschn** [4tals/LinksForIsrael#539]
These generally go together - when you want supplies, you need to transport them.
The new category could be something like "ציוד ושינוע" with sub-categories like "transportation" and "equipment"

We also need to think about the "Reserve" category - vast majority of relevant efforts (like equipment) is geared towards soldiers and reserves anyway, I suspect we can disperse the few initiatives there to the other existing categories.

**Comment by 4tal** [comment]
Agree with @ohadschn. What should be the high level name?

**Comment by 4tal** [comment]
The proper term is logistics, but most of the people will not understand exactly. I vote for "Supply & Transportation"
ציוד ושינוע

**Comment by sophieb805** [comment]
@ohadschn @4tal but then the food needs to remain a separate category. There'll be ציוד ושינוע and אוכל or מזון by itself

**Comment by ohadschn** [comment]
> @ohadschn @4tal but then the food needs to remain a separate category. There'll be ציוד ושינוע and אוכל or מזון by itself or it can be 1 category: מזון, ציוד ושינוע

I vote for a single category for all of them - food is a "kind of" equipment...

**Comment by 4tal** [comment]
Done
