### ISSUE TITLE
Reorder & organize technology categories

### ISSUE THREAD

**Issue by ohadschn** [4tals/LinksForIsrael#542]
* Some are in the wrong category - for example "Israel diplomacy"
* Some are too niche and should be removed, for example "סיווג טקסט פרו/אנטי-ישראלי" (only ~50 members in the group)
* Some are only meant for organizations and should be removed: moked arava
* We should have a "tech incubator" category where we'd place BuildToSupport and similar

**Comment by 4tal** [comment]
Done
