### ISSUE TITLE
Category names do not match their content

### ISSUE THREAD

**Issue by ohadschn** [4tals/LinksForIsrael#610]
Following the recent category organization and renames, we are left in a state where the names don't always match the meaning.
For example, the `Children` category should actually be `Family` now - we need to go over all categories and Sub categories to make sure their names match, otherwise people suggesting new initiatives will use the wrong categories.

**Comment by 4tal** [comment]
And we need route old categories names current categories.

**Comment by ohadschn** [comment]
> And we need route old categories names current categories.

Good catch - but note that we already know how (it's pretty simple): 
https://github.com/4tals/LinksForIsrael/issues/356#issuecomment-1812848704
