### ISSUE TITLE
[UPDATE-INITIATIVE]: חמ״ל אזרחי - סיוע לתושבי קו הלחימה

### ISSUE THREAD

**Issue by 4tal** [4tals/LinksForIsrael#616]
### Initiative Name

KhamalAmEhad

### Initiative Description

זקוקים לסיוע? יכולים להציע עזרה? חמ״ל אזרחי מאחד את כל היוזמות עבור המשפחות והחיילים, בחזית ובעורף.  חמ"ל אזרחי אחד - עם אחד

### Initiative Details

החמ"ל האזרחי - עוזרים לצה״ל לנצח ותומכים מכל הלב באזרחים
7 באוקטובר 2023 ישראל התעוררה למלחמה קשה.
מתוך הזוועה והשבר, על פי מיטב הרוח הישראלית - כי אנחנו עם אחד, קם החמ״ל האזרחי - מרכז ההתנדבות הגדול בישראל.

החמ״ל האזרחי הוא התארגנות פועלת בהתנדבות מלאה לתת מענה לכל צורך של התושבים והחיילים:
חילוץ ופינוי תושבים מקו האש לאיזורים בטוחים, איסוף ושינוע של ציודים חסרים, חיבור בין משפחות שנותרו חסרות כל למשפחות מארחות, שרותי הסעות, סיוע באיתור הנעדרים, סיוע לתושבי קו הלחימה, גיוס תרומות לתושבי העוטף, תמיכה נפשית, ועוד. אנו מקבלים בקשות לסיוע, ומחברים למתנדבים ולארגונים שיכולים לסייע. בשבוע הראשון למלחמה פינינו מאות תושבים מקו העימות, חיברנו בין אלפי משפחות ומארחים מתאימים, אספנו ושינענו אלפי ארגזים של ציוד בסיסי ומזון עבור חיילי צה״ל ותושבים מפונים, נתנו סיוע לתושבי הדרום, הסענו מאות תושבים וחיילים ליעדם, הענקנו תמיכה וליווי למשפחות שכולות, והכי חשוב: ריכזנו את כל היוזמות תחת קורת גג אחת. עם אחד, חמ״ל אזרחי אחד. 

חמ״ל אזרחי מבטיח שלא תישאר בקשה אחת שלא תקבל מענה. 

אם אתם זקוקים לסיוע בכל תחום שהוא, אל תהססו למלא את הטופס המתאים, החמ"ל האזרחי ידאג לחבר אתכם עם מערך המתנדבים שלנו מהר ככל שניתן. אם ביכולתכם להתנדב, לארח, להסיע, לתמוך, לתת סיוע לתושבי הדרום והצפון - אנא מלאו את פרטיכם כדי שנוכל לקשר אתכם למי שזקוק לסיוע.
יש לנו עם אחד, ומדינה אחת. זה הזמן לאחד כוחות ולפעול - יחד ננצח במלחמה!

עם ישראל חי!

### Initiative Validation Details

Known initiative, verified by @4tal

### Initiative Category

GeneralAssistance

### Initiative main URL

https://www.hamal.org.il/

### Initiative Logo

https://static.wixstatic.com/media/dea07e_2159e1a1df9d4b5097955583837debb2~mv2.png/v1/fill/w_108,h_70,fp_0.50_0.50,q_85,usm_0.66_1.00_0.01,enc_auto/logoHamal%201.png

### Initiative Website

https://www.hamal.org.il/

### Initiative Donation Link

https://meshulam.co.il/purchase?b=d635b86acaf6057aa68cb24da64b35c0

**Comment by ohadschn** [comment]
We already have it for a long time

**Comment by 4tal** [comment]
Where, it's under agriculture and it's fit much more for general Assistance

**Comment by ohadschn** [comment]
> https://www.hamal.org.il/

Here, it's under the old name and URL (which redirects to this one):
https://github.com/4tals/LinksForIsrael/blob/4abd99c8ea912b381f745fa0b72a5b7e0292e022/_data/links/GeneralAssistance/links.json#L40

I guess we can update it
