### ISSUE TITLE
[NEW-INITIATIVE]: Scooper - ניטור ומחקר ברשת

### ISSUE THREAD

**Issue by 4tal** [4tals/LinksForIsrael#623]
### Initiative Name

Scooper - ניטור ומחקר ברשת

### Initiative Description

ניתור ומחקר ברשת, מאפשר לראות פוסטים טרנדים לפי איזורים ופוסטים עם הכי הרבה מעורבות

### Initiative Details

ניתור ומחקר ברשת, מאפשר לראות פוסטים טרנדים לפי איזורים ופוסטים עם הכי הרבה מעורבות

### Initiative Validation Details

Verified Manually by @4tal 

### Initiative Category

StrategicCommunication/Tools

### Initiative main URL

https://access.scooper.co.il/app/project/7821ad26-cc00-4a3f-998b-a3521c2f7cfe/shared_dashboard/export_Scooper6_hVq6X5yN.html#/SHARED_DASHBOARD#co=project&cid=7821ad26-cc00-4a3f-998b-a3521c2f7cfe&psid=export_Scooper6_hVq6X5yN.html&keyid=undefined&data=eyJyIjp7ImEiOnsiYWN0aXZlUGFnZUlkIjoiREVGQVVMVC1EQVNILVNFQ1RJT04ifSwiaSI6IlNIQVJFRF9EQVNIQk9BUkQiLCJzIjpbXX19

### Initiative Logo

https://access.scooper.co.il/app/image/ae8a9c0a-2f60-4b7a-b00e-25332e68583a

### Initiative Website

https://access.scooper.co.il/app/project/7821ad26-cc00-4a3f-998b-a3521c2f7cfe/shared_dashboard/export_Scooper6_hVq6X5yN.html#/SHARED_DASHBOARD#co=project&cid=7821ad26-cc00-4a3f-998b-a3521c2f7cfe&psid=export_Scooper6_hVq6X5yN.html&keyid=undefined&data=eyJyIjp7ImEiOnsiYWN0aXZlUGFnZUlkIjoiREVGQVVMVC1EQVNILVNFQ1RJT04ifSwiaSI6IlNIQVJFRF9EQVNIQk9BUkQiLCJzIjpbXX19

**Comment by ohadschn** [comment]
@4tal agriculture category??
