### ISSUE TITLE
מתאם ציוד ואספקה

### ISSUE THREAD

**Issue by omerspenser** [4tals/LinksForIsrael#639]
### Initiative Name

מתאם ציוד ואספקה

### Initiative Description

פלטפורמה לחיבור בין ספקים לאנשים שצריכים ציוד

### Initiative Details

פלטפורמה שמחברת בין חיילים ואזרחים שצריכים ציוד, לחמ״לים ומתנדבים שיכולים לעזור ולספק

### Initiative Validation Details

Operations volunteer, opening initiatives from the excel spreadsheet.

### Initiative Category

Supplies/Donation

### Initiative main URL

https://supply-match.com

### Initiative Logo

https://supply-match.com/assets/Social-0b740862.png

**Comment by 4tal** [comment]
Not relevant
