### ISSUE TITLE
[NEW-INITIATIVE]: jgive

### ISSUE THREAD

**Issue by omerspenser** [4tals/LinksForIsrael#644]
### Initiative Name

JGive

### Initiative Description

קרן חירום לאומית לסיוע לנפגעי המלחמה

### Initiative Details
קרן החירום הלאומית הוקמה על ידי שותפים יחד עם JGive במטרה להעניק סיוע לנפגעים במלחמה הקשה שפקדה אותנו. כל כספי התרומות שייאספו בקרן, יחולקו לעמותות המציעות שירותי סעד, רווחה, ציוד, מזון ועוד לנפגעי המלחמה. הכספים יחולקו באמצעות ועדה ציבורית בראשות אליעזר שקדי (אלוף במיל').

העמותות הפועלות בגזרות השונות מכירות מקרוב את האתגרים ואת דרכי הפעולה האפשריות. תמיכה בהם היא הדרך הטובה ביותר שאנו מכירים כדי להשפיע, ולו במעט, על חייהם של רבים. הצטרפו אלינו ותרמו.

כל התרומות מוכרות לפי סעיף 46. 
הכסף עובר במלואו , למעט עמלת סליקת האשראי במקרה של תרומה באשראי

### Initiative Validation Details

Operations volunteer.

### Initiative Category

Donations/Main

### Initiative main URL

https://www.jgive.com/new/he/ils/donation-targets/110048?utm_source=homepage

### Initiative Logo

https://assets-global.website-files.com/61ffb95380517e7a4edf46cf/65532fbcd073b483a88f4edb_Logo.png

### Initiative Website

https://www.jgive.com/new/he/ils/donation-targets/110048?utm_source=homepage

### Initiative E-Mail

circle@jgive.com

**Comment by ohadschn** [comment]
@omerspenser the URL points to a specific campaign, which as explained in the other ticket we try and avoid. 
On the other hand, adding the entire site would be too generic - we try and focus on iron-swords related initiative.
Having said that, adding a few special key/main campaigns (typically comprised out of multiple orgzniations and raising very large sums) could make sense, in this case perhaps: https://www.jgive.com/new/he/ils/donation-targets/110048?utm_source=homepage

**Comment by ohadschn** [comment]
@omerspenser thank you, I've made a couple of small updates
BTW what do you mean by "operations volunteer" in the validation details?
