### ISSUE TITLE
[NEW-INITIATIVE]: SocialSolidarityHome

### ISSUE THREAD

**Issue by omerspenser** [4tals/LinksForIsrael#647]
### Initiative Name

הבית לסולידריות חברתית

### Initiative Description

מוקד מידע לעסקים

### Initiative Details

בימים קשים אלו הבית לסולידריות חברתית מטעם קרן משפחת שעשוע עומדים לצד העסקים בישראל

### Initiative Validation Details

Operations volunteer

### Initiative Category

Donations/Economy

### Initiative main URL

https://www.solidarity-foundation.org.il/ironswords

### Initiative Website

https://www.solidarity-foundation.org.il/ironswords

### Initiative E-Mail

info@solidarity-foundation.org.il

### Initiative WhatsApp

https://api.whatsapp.com/send?phone=972523299519

### Initiative Form

https://forms.gle/XH27b88nx9ynXqS36

### Initiative Facebook

https://www.facebook.com/wer1solidarity

### Initiative Instagram

https://www.instagram.com/social_solidarity_il/?utm_medium=copy_link

### Initiative LinkedIn

https://www.linkedin.com/company/the-social-solidarity-foundation/

### Initiative YouTube Page / Channel

https://www.youtube.com/channel/UCooKVLFJQOvggvuklgYwq_w

**Comment by ohadschn** [comment]
@omerspenser please update the information per: https://www.solidarity-foundation.org.il/ironswords
In other words, our site is iron-swords oriented - and in this case they have a special page, whatsapp group, form etc.

**Comment by ohadschn** [comment]
@omerspenser thank you, I've made a couple of small updates
BTW what do you mean by "operations volunteer" in the validation details?

**Comment by omerspenser** [comment]
I'm not sure what to put there so I just described myself :)

**Comment by ohadschn** [comment]
> I'm not sure what to put there so I just described myself :)

There is no need to, we can see who opened the ticket :)
The idea is to describe what you did to validate the authenticity of the initiative - for example, you know the creator personally, you read about them in the paper (in that case, link to the article), etc.
