### ISSUE TITLE
[NEW-INITIATIVE]: חרבות AI

### ISSUE THREAD

**Issue by DanielShterenberg** [4tals/LinksForIsrael#654]
### Initiative Name
Haravot AI

### Initiative Description
נרתמים למען ההסברה הישראלית - מדובבים את הסרטונים שלכם!

### Initiative Details
באתר זה אתם יכולים להעלות סרטון הסברה שלכם מדברים בעברית, ובעזרת AI אנחנו נדבב את הסרטון לשפה שתבחרו. הדיבוב יוצא בצורה טובה מאוד! תואם לקול שלכם מהסרטון שהעליתם ותואם בשפתיים לנאמר. בקרוב יהיה ניתן גם לשלוט ברמת המבטא וגם להוסיף תרגום (כתוביות). השירות זמין כרגע בחינם לכל הארץ עקב המצב.

### Initiative Validation Details
https://htmag.co.il/haravot.html

### Initiative Category
StrategicCommunication/Tools

### Initiative Main URL
https://haravot.com/

### Initiative Logo
https://haravot.com/wp-content/uploads/2023/10/haravot-full-colorLogo.png

### Initiative Website
https://haravot.com/

### Initiative Document
https://haravot.com/%d7%90%d7%99%d7%9a-%d7%99%d7%95%d7%a6%d7%a8%d7%99%d7%9d-%d7%a1%d7%a8%d7%98%d7%95%d7%9f-%d7%94%d7%a1%d7%91%d7%a8%d7%94-%d7%9e%d7%95%d7%a9%d7%9c%d7%9d-%d7%93%d7%a8%d7%9a-%d7%9e%d7%a2%d7%a8%d7%9b%d7%aa-a/

### Initiative Instagram
https://www.instagram.com/haravot_ai/

### Initiative YouTube Page / Channel
https://vimeo.com/user209999187

**Comment by ohadschn** [comment]
Already exists
