### ISSUE TITLE
Make swipe buttons clickable

### ISSUE THREAD

**Issue by Tamir198** [4tals/LinksForIsrael#664]
Hey, can those buttons be clickable?  

![image](https://github.com/4tals/LinksForIsrael/assets/34707669/94a7e2c7-c168-479f-ae83-19c1816dd951)

I could not understand why I can't click those buttons at first, I think it could be better UX if they were clickable

**Comment by ohadschn** [comment]
> Hey, can those buttons be clickable?
> I could not understand why I can't click those buttons at first, I think it could be better UX if they were clickable

@Tamir198 Is this a duplicate of https://github.com/4tals/LinksForIsrael/issues/592?

**Comment by Tamir198** [comment]
Oh ye I missed it
