### ISSUE TITLE
[NEW-INITIATIVE]: Shoreshfund 

### ISSUE THREAD

**Issue by omerspenser** [4tals/LinksForIsrael#685]
### Initiative Name

קרן שורש

### Initiative Description

קרן סיוע למשפחות שנפגעו בקו העימות

### Initiative Details

קרן שורש ממקדת את פעילותה בסיוע חירום למשפחות שנפגעו בקו העימות.
הקרן מפנה תרומות למשפחות כדי לסייע להן להתמודד עם צרכי
היום-יום הקיומיים עד לכניסת מנגנוני המדינה לפעולה.

### Initiative Validation Details

Shoresh fund is actually using Jgive and GiveBack platforms for its donations so I'm not sure how relevant it is.

### Initiative Category

Economic/Donations

### Initiative main URL

https://www.shoreshfund.org/he

### Initiative Logo

https://static.wixstatic.com/media/09d1b0_6aa775a8bafe49c0a7818dfca3bc5d06~mv2.png/v1/fill/w_458,h_154,al_c,q_85,usm_0.66_1.00_0.01,enc_auto/Shoresh%20(2)-02.png

### Initiative Website

https://www.shoreshfund.org/he

### Initiative Phone Number

+972 51 2634043

**Comment by ohadschn** [comment]
@omerspenser as you have implied, it is less relevant for us - we try to avoid "donation only" initiatives, and rather direct our visitors to donation aggregators and validators like SafeDonate
