### ISSUE TITLE
[NEW-INITIATIVE]: שבעה באוקטובר - האהובים שאיבדנו

### ISSUE THREAD

**Issue by omerspenser** [4tals/LinksForIsrael#689]
### Initiative Name

OctSevenLostLovedOnes

### Initiative Description

אתר הנצחה לנופלים ב7 באקוטובר ובמלחמת חרבות ברזל

### Initiative Details

מתקפת הטרור באותה שבת שחורה ומלחמת "חרבות ברזל" שבאה בעקבותיה הותירו חלל עצום הנוגע בכל בית בישראל, בכל לב אנושי.  האתר הוקם כבית לתמונות ולסיפורים של האנשים היקרים שנקטפו בטרם עת. 

### Initiative Validation Details

https://www.linkedin.com/feed/update/urn:li:activity:7129843344486072320/

### Initiative Category

MemorialRemembrance/Main

### Initiative main URL

https://octseven.co.il

### Initiative Logo

https://octseven.co.il/static/media/flowers.05f384a2aad3ebb1a6b1.png

### Initiative Website

https://octseven.co.il

### Initiative E-Mail

support@octseven.com

**Comment by ohadschn** [comment]
@omerspenser thank you, please see some small changes I made (most importantly validation details)
