### ISSUE TITLE
"Information concentration" category is too crowded - unify some links & split other out to a new "aggregators" category

### ISSUE THREAD

**Issue by ohadschn** [4tals/LinksForIsrael#69]
1. I think we should add an additional, separate category for link aggregators, and it should be relatively at the bottom (seeing as their links would probably be contained in ours anyway - but it wouldn't hurt to double check that along the way). 
   * Move "Hamal Am 1" to it
   * Move "IsraeHelp" to it
   * Add https://linktr.ee/cherevotbarzel to it (I don't see it in our links currently)
   * Add https://linktr.ee/arvot (got it from the above aggregator... hopefully they don't link to aggregators too or my BFS will never end)
   * https://t.me/thedavidarmy
2. Only have one link for "general citizen aid organization" (that contains all areas), or at least have some collapsible sublinks that don't take up as much space as 4 different links. Come to think of it, maybe we need to add a concept of collapsible sub-sections in general, for example in "Family Hosting" we have such sub-sections but they are not collapsible so again take up a lot of space.

**Comment by 4tal** [comment]
Looks good

**Comment by 4tal** [comment]
not relevant.
