### ISSUE TITLE
[NEW-INITIATIVE]: BooksForSoldiers

### ISSUE THREAD

**Issue by omerspenser** [4tals/LinksForIsrael#691]
### Initiative Name

ספרים וספריות ללוחמים

### Initiative Description

קבוצת וואטסאפ להעברת ספרים וספריות ללוחמים

### Initiative Details

קבוצת וואטסאפ להעברת ספרים וספריות ללוחמים

### Initiative Validation Details

.

### Initiative Category

SuppliesAndTransportation/EquipmentAndFood

### Initiative main URL

https://chat.whatsapp.com/E0m1ez0ShyCBPfFoh66cTg

### Initiative WhatsApp

https://chat.whatsapp.com/E0m1ez0ShyCBPfFoh66cTg

**Comment by ohadschn** [comment]
Initiative is too small, the WhatsApp group has only 64 members - if and when it becomes more substantial we can reconsider.
