### ISSUE TITLE
[NEW-INITIATIVE]: SupportFromHome

### ISSUE THREAD

**Issue by omerspenser** [4tals/LinksForIsrael#693]
### Initiative Name

תומכים מהבית - סיוע לחיילים

### Initiative Description

קבוצת וואטסאפ להעברת מוצרי מזון למוצבים/בסיסים

### Initiative Details

תומכים מהבית - סיוע לחיילים - העברת מוצרי מזון למוצבים/בסיסים

### Initiative Validation Details

Please check the logo because I did a kombina so not sure if it works.

### Initiative Category

GeneralAssistance

### Initiative main URL

https://chat.whatsapp.com/DyVgn7FHpr73y9PilAfCI9

### Initiative Logo

https://im.ge/i/EdzwH6

### Initiative WhatsApp

https://chat.whatsapp.com/DyVgn7FHpr73y9PilAfCI9

**Comment by ohadschn** [comment]
As you can see in the comment above, we already have it
