### ISSUE TITLE
[NEW-INITIATIVE]: HelpingReservistsFamailies

### ISSUE THREAD

**Issue by omerspenser** [4tals/LinksForIsrael#696]
### Initiative Name

תומכים מהבית - עוזרים למשפחות המילואימניקים

### Initiative Description

יוזמה לתמיכה במשפחות המילואימניקים

### Initiative Details

ביום שבת 7.10.2023, פרצה מלחמה בישראל והתעוררנו למציאות חדשה ואכזרית.  
 
רבים ורבות מאיתנו עזבו הכול מיד, השאירו את היקרים להם מכול בעורף והתייצבו לעמוד לצד חבריהם לנשק במערכה הקשה.  
אנו יוצאי־ות היחידות הקרביות והמודיעיניות, מסייעים בכל הנדרש למשפחות המילואמינקים־יות בהבנה שלפנינו אירוע מתגלגל המשתנה מדי שעה.
אנחנו, תומכים־ות מהבית נעשה הכול כדי שאף אחד לא ישאר לבד. 

### Initiative Validation Details

https://www.facebook.com/tomchimmehabait

### Initiative Category

FamilyAndPets/Main

### Initiative main URL

https://www.miluimnik.org

### Initiative Website

https://www.miluimnik.org

### Initiative Phone Number

073 2272 182

### Initiative WhatsApp

https://chat.whatsapp.com/D5PH3yDjcJa2wB2oDnHeZC

### Initiative Facebook

https://www.facebook.com/tomchimmehabait

**Comment by ohadschn** [comment]
As you can see in the comment above, we already have it
