### ISSUE TITLE
Normalize markdown/link format

### ISSUE THREAD

**Issue by ohadschn** [4tals/LinksForIsrael#70]
This would have to be a prerequisite for https://github.com/4tal/LinksForIsrael/issues/68

1.In some cases we have description below the link, in other above
2. Sometimes there's space between the link buttons, sometimes there's not
3. Sometimes there are separators between links, sometimes not
4. Sometimes there are bullets (`•`) before the descriptions, sometimes there aren't

**Comment by 4tal** [comment]
Not prioritize until we'll see better site structure

**Comment by 4tal** [comment]
Done
