### ISSUE TITLE
[NEW-INITIATIVE]: מחבקים את המילואימניקים

### ISSUE THREAD

**Issue by DanielShterenberg** [4tals/LinksForIsrael#715]
### Initiative Name
HuggingTheReserveSoldiers

### Initiative Description
רשימה מסודרת של עסקי מילאומניקים

### Initiative Details
יש ברשימה בתי קפה ומסעדות, עורכי דין, מאמני כושר, מובילים, נגרים ומה לא - שהבעלים שלהם נמצאים גם כעת עמוק בעזה או ישנים באוהלים בגבול הצפון כבר מעל 70 יום, ומגיע להם שנקנה אצלם, מגיע להם שנחבק אותם. חלקם אמנם לא יכולים לתת שירות מיידי כי הם לא בזמינות (יש למשל שף פרטי שנמצא בלחימה. אחיו נהרג כשיצא מעזה והוא ממשיך להילחם), אבל הם ישמחו שתבקרו אצלם באתר, תתרשמו ותרשמו להיות לקוחות שלהם בעתיד. אפרת בדקה ודיברה עם כל המילאומניקים (והמילואמניקיות) ברשימה (או עם בני המשפחה שלהם), יש בלינק דרכים ליצירת קשר,  ואפשר גם לעשות חיפוש דרך אפליקציית איזי כדי לדעת מה מהם קרוב אליכם.

### Initiative Validation Details
יוזמה בשיתוף אפליקציית EASY

### Initiative Category
Economic/Businesses

### Initiative Main URL
https://go.easy.co.il/Hanoch

### Initiative Logo
https://media.easy.co.il/images/banners/1701364082263-banner.png

### Initiative Website
https://go.easy.co.il/Hanoch

**Comment by ohadschn** [comment]
@4tal I added this (forwarded in an MS internal group)
