### ISSUE TITLE
Add yet another consumer/producer matcher: https://app.simplerstory.com/story/y-LBgBnM8

### ISSUE THREAD

**Issue by ohadschn** [4tals/LinksForIsrael#72]
Got it from Alex's site (https://linktr.ee/cherevotbarzel) so should be legit, also looks good

**Comment by ohadschn** [comment]
@DanielShterenberg please see if you can reach the Google employee listed at the bottom of that link
If you manage to do so and validate both authenticity and relevance of this initiative, please add it by editing the issue to match the format our bot expects (for example https://github.com/4tals/LinksForIsrael/issues/387):
1. title
2. body
3. label

**Comment by DanielShterenberg** [comment]
I suppose we can close this one right?
@ohadschn

**Comment by ohadschn** [comment]
> I suppose we can close this one right? @ohadschn

Yeah I think so - last entry I see there was from ~3 weeks ago, and it looks pretty basic compared to the other similar sites.
if you ever hear back from your colleague we can re-open...
