### ISSUE TITLE
Switch to Pages View And not Collapsible lists

### ISSUE THREAD

**Issue by 4tal** [4tals/LinksForIsrael#77]

**Comment by ohadschn** [comment]
@4tal could you elaborate?
What does "pages view" mean?
I had an idea that we'll the 2-3 most important links in the main list, and then have a `more...` linking to a dedicated page with more links - is this similar to what you're suggesting here?

**Comment by oriharel** [comment]
Is there an updated figma for the Pages View?

**Comment by 4tal** [comment]
@oriharel Not yet.

**Comment by 4tal** [comment]
Kind of done, with external portals like weapon or Tech

**Comment by ohadschn** [comment]
I don't think the original issue is resolved, the idea here is to have multiple link pages (similar to the main one):

> keep the 2-3 most important links in the main list, and then have a `more...` linking to a dedicated page with more links 
> We could add a property to the JSON like `primaryLink` which would govern whether the link stays in the main page or sent out to the dedicated/separate page.

**Comment by 4tal** [comment]
https://www.figma.com/proto/BxHCYKopVxDdMmuIoOQ0AL/Look-and-Feel?type=design&node-id=27-16402&t=ugbQ0lOoJ6Phdrb8-0&scaling=scale-down-width&page-id=0%3A1&starting-point-node-id=27%3A16402



![Image](https://github.com/4tals/LinksForIsrael/assets/6404507/d2bcc9c9-0c71-43a9-9027-6d919f988bb6)

**Comment by ohadschn** [comment]
> https://www.figma.com/proto/BxHCYKopVxDdMmuIoOQ0AL/Look-and-Feel?type=design&node-id=27-16402&t=ugbQ0lOoJ6Phdrb8-0&scaling=scale-down-width&page-id=0%3A1&starting-point-node-id=27%3A16402
> 
> ![Image](https://user-images.githubusercontent.com/6404507/276675624-d2bcc9c9-0c71-43a9-9027-6d919f988bb6.png)

And in this design, we won't have dedicated pages that you actually navigate to?
Everything would remain on the main page?
