### ISSUE TITLE
Remove tag from the link in case someone used link with tag and then, continue to click on other sections in the site

### ISSUE THREAD

**Issue by 4tal** [4tals/LinksForIsrael#91]

**Comment by 4tal** [comment]
If user reach to the site from certain link, then keep scrolling and focus on another category it's weird if he'll copy paste site url and the old tag will be there.

Ofc he can click again on the copy but even due it's should not stay there

**Comment by yanai101** [comment]
I think that issue is relevant to this PR:
https://github.com/4tal/LinksForIsrael/pull/175

**Comment by ohadschn** [comment]
@4tal could you clarify?? is this still relevant???

**Comment by 4tal** [comment]
Not relevant anymore
