### ISSUE TITLE
Move descriptions to hovers so they take up less space

### ISSUE THREAD

**Issue by ohadschn** [4tals/LinksForIsrael#93]
Make sure the "name" is descriptive enough so most of the information is there, and the hover is only for more details

**Comment by ohadschn** [comment]
@4tal it looks like this has been implemented, but at the cost of an important capability - we now cannot search description text.
To clarify, before the change, I could search `foo` using the browser search, and if the latter was present in any description, it would jump to that location and even auto-expand it. Now I have to search the GitHub repo...

**Comment by 4tal** [comment]
Not Relevant

**Comment by ohadschn** [comment]
Why not?
I think they still take up too much space... example:
![image](https://github.com/4tals/LinksForIsrael/assets/8555641/5ca991fe-8ce1-4f71-9a03-8df986d4e53e)

**Comment by ohadschn** [comment]
Superseded by https://github.com/4tals/LinksForIsrael/issues/251
