### ISSUE TITLE
Get basic donation

### ISSUE THREAD

**Issue by galbit** [4tals/LinksForIsrael#97]

**Comment by ohadschn** [comment]
@galbit could you elaborate?

**Comment by 4tal** [comment]
@ohadschn Add Simple button to point to https://payboxapp.page.link/y9GzTqgMFGyz9GVCA

**Comment by ohadschn** [comment]
> @ohadschn Add Simple button to point to https://payboxapp.page.link/y9GzTqgMFGyz9GVCA

I think as long as the war is going on it's not really necessary, as the costs for a few months are pretty low no?
After the war is over, if we want to do something else with the site we can cross that bridge when we get to it...

**Comment by 4tal** [comment]
<img width="1490" alt="image" src="https://github.com/4tals/LinksForIsrael/assets/6404507/9c3f10fc-9c4b-41bd-bd47-671fd9d9cc18">

I'm about to move back with my parents.
